// Code generated by GREENPACK (github.com/glycerine/greenpack). DO NOT EDIT.

package types

import (
	"github.com/glycerine/greenpack/msgp"
)

// DecodeMsg implements msgp.Decodable
// We treat empty fields as if we read a Nil from the wire.
func (z *Auction) DecodeMsg(dc *msgp.Reader) (err error) {
	var sawTopNil bool
	if dc.IsNil() {
		sawTopNil = true
		err = dc.ReadNil()
		if err != nil {
			return
		}
		dc.PushAlwaysNil()
	}

	var field []byte
	_ = field
	const maxFields0zgensym_e3caedb3b7ec15ca_1 = 10

	// -- templateDecodeMsg starts here--
	var totalEncodedFields0zgensym_e3caedb3b7ec15ca_1 uint32
	totalEncodedFields0zgensym_e3caedb3b7ec15ca_1, err = dc.ReadMapHeader()
	if err != nil {
		return
	}
	encodedFieldsLeft0zgensym_e3caedb3b7ec15ca_1 := totalEncodedFields0zgensym_e3caedb3b7ec15ca_1
	missingFieldsLeft0zgensym_e3caedb3b7ec15ca_1 := maxFields0zgensym_e3caedb3b7ec15ca_1 - totalEncodedFields0zgensym_e3caedb3b7ec15ca_1

	var nextMiss0zgensym_e3caedb3b7ec15ca_1 int32 = -1
	var found0zgensym_e3caedb3b7ec15ca_1 [maxFields0zgensym_e3caedb3b7ec15ca_1]bool
	var curField0zgensym_e3caedb3b7ec15ca_1 string

doneWithStruct0zgensym_e3caedb3b7ec15ca_1:
	// First fill all the encoded fields, then
	// treat the remaining, missing fields, as Nil.
	for encodedFieldsLeft0zgensym_e3caedb3b7ec15ca_1 > 0 || missingFieldsLeft0zgensym_e3caedb3b7ec15ca_1 > 0 {
		//fmt.Printf("encodedFieldsLeft: %v, missingFieldsLeft: %v, found: '%v', fields: '%#v'\n", encodedFieldsLeft0zgensym_e3caedb3b7ec15ca_1, missingFieldsLeft0zgensym_e3caedb3b7ec15ca_1, msgp.ShowFound(found0zgensym_e3caedb3b7ec15ca_1[:]), decodeMsgFieldOrder0zgensym_e3caedb3b7ec15ca_1)
		if encodedFieldsLeft0zgensym_e3caedb3b7ec15ca_1 > 0 {
			encodedFieldsLeft0zgensym_e3caedb3b7ec15ca_1--
			field, err = dc.ReadMapKeyPtr()
			if err != nil {
				return
			}
			curField0zgensym_e3caedb3b7ec15ca_1 = msgp.UnsafeString(field)
		} else {
			//missing fields need handling
			if nextMiss0zgensym_e3caedb3b7ec15ca_1 < 0 {
				// tell the reader to only give us Nils
				// until further notice.
				dc.PushAlwaysNil()
				nextMiss0zgensym_e3caedb3b7ec15ca_1 = 0
			}
			for nextMiss0zgensym_e3caedb3b7ec15ca_1 < maxFields0zgensym_e3caedb3b7ec15ca_1 && (found0zgensym_e3caedb3b7ec15ca_1[nextMiss0zgensym_e3caedb3b7ec15ca_1] || decodeMsgFieldSkip0zgensym_e3caedb3b7ec15ca_1[nextMiss0zgensym_e3caedb3b7ec15ca_1]) {
				nextMiss0zgensym_e3caedb3b7ec15ca_1++
			}
			if nextMiss0zgensym_e3caedb3b7ec15ca_1 == maxFields0zgensym_e3caedb3b7ec15ca_1 {
				// filled all the empty fields!
				break doneWithStruct0zgensym_e3caedb3b7ec15ca_1
			}
			missingFieldsLeft0zgensym_e3caedb3b7ec15ca_1--
			curField0zgensym_e3caedb3b7ec15ca_1 = decodeMsgFieldOrder0zgensym_e3caedb3b7ec15ca_1[nextMiss0zgensym_e3caedb3b7ec15ca_1]
		}
		//fmt.Printf("switching on curField: '%v'\n", curField0zgensym_e3caedb3b7ec15ca_1)
		switch curField0zgensym_e3caedb3b7ec15ca_1 {
		// -- templateDecodeMsg ends here --

		case "id_zid00_u64":
			found0zgensym_e3caedb3b7ec15ca_1[0] = true
			z.ID, err = dc.ReadUint64()
			if err != nil {
				return
			}
		case "itemName_zid01_str":
			found0zgensym_e3caedb3b7ec15ca_1[1] = true
			z.ItemName, err = dc.ReadString()
			if err != nil {
				return
			}
		case "description_zid02_str":
			found0zgensym_e3caedb3b7ec15ca_1[2] = true
			z.Description, err = dc.ReadString()
			if err != nil {
				return
			}
		case "initialBid_zid03_u64":
			found0zgensym_e3caedb3b7ec15ca_1[3] = true
			z.InitialBid, err = dc.ReadUint64()
			if err != nil {
				return
			}
		case "reserve_zid04_u64":
			found0zgensym_e3caedb3b7ec15ca_1[4] = true
			z.Reserve, err = dc.ReadUint64()
			if err != nil {
				return
			}
		case "dataTime_zid05_i64":
			found0zgensym_e3caedb3b7ec15ca_1[5] = true
			z.DateTime, err = dc.ReadInt64()
			if err != nil {
				return
			}
		case "expires_zid06_i64":
			found0zgensym_e3caedb3b7ec15ca_1[6] = true
			z.Expires, err = dc.ReadInt64()
			if err != nil {
				return
			}
		case "seller_zid07_u64":
			found0zgensym_e3caedb3b7ec15ca_1[7] = true
			z.Seller, err = dc.ReadUint64()
			if err != nil {
				return
			}
		case "category_zid08_u64":
			found0zgensym_e3caedb3b7ec15ca_1[8] = true
			z.Category, err = dc.ReadUint64()
			if err != nil {
				return
			}
		case "extra_zid09_str":
			found0zgensym_e3caedb3b7ec15ca_1[9] = true
			z.Extra, err = dc.ReadString()
			if err != nil {
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				return
			}
		}
	}
	if nextMiss0zgensym_e3caedb3b7ec15ca_1 != -1 {
		dc.PopAlwaysNil()
	}

	if sawTopNil {
		dc.PopAlwaysNil()
	}

	if p, ok := interface{}(z).(msgp.PostLoad); ok {
		p.PostLoadHook()
	}

	return
}

// fields of Auction
var decodeMsgFieldOrder0zgensym_e3caedb3b7ec15ca_1 = []string{"id_zid00_u64", "itemName_zid01_str", "description_zid02_str", "initialBid_zid03_u64", "reserve_zid04_u64", "dataTime_zid05_i64", "expires_zid06_i64", "seller_zid07_u64", "category_zid08_u64", "extra_zid09_str"}

var decodeMsgFieldSkip0zgensym_e3caedb3b7ec15ca_1 = []bool{false, false, false, false, false, false, false, false, false, false}

// fieldsNotEmpty supports omitempty tags
func (z *Auction) fieldsNotEmpty(isempty []bool) uint32 {
	if len(isempty) == 0 {
		return 10
	}
	var fieldsInUse uint32 = 10
	isempty[0] = (z.ID == 0) // number, omitempty
	if isempty[0] {
		fieldsInUse--
	}
	isempty[1] = (len(z.ItemName) == 0) // string, omitempty
	if isempty[1] {
		fieldsInUse--
	}
	isempty[2] = (len(z.Description) == 0) // string, omitempty
	if isempty[2] {
		fieldsInUse--
	}
	isempty[3] = (z.InitialBid == 0) // number, omitempty
	if isempty[3] {
		fieldsInUse--
	}
	isempty[4] = (z.Reserve == 0) // number, omitempty
	if isempty[4] {
		fieldsInUse--
	}
	isempty[5] = (z.DateTime == 0) // number, omitempty
	if isempty[5] {
		fieldsInUse--
	}
	isempty[6] = (z.Expires == 0) // number, omitempty
	if isempty[6] {
		fieldsInUse--
	}
	isempty[7] = (z.Seller == 0) // number, omitempty
	if isempty[7] {
		fieldsInUse--
	}
	isempty[8] = (z.Category == 0) // number, omitempty
	if isempty[8] {
		fieldsInUse--
	}
	isempty[9] = (len(z.Extra) == 0) // string, omitempty
	if isempty[9] {
		fieldsInUse--
	}

	return fieldsInUse
}

// EncodeMsg implements msgp.Encodable
func (z *Auction) EncodeMsg(en *msgp.Writer) (err error) {
	if p, ok := interface{}(z).(msgp.PreSave); ok {
		p.PreSaveHook()
	}

	// honor the omitempty tags
	var empty_zgensym_e3caedb3b7ec15ca_2 [10]bool
	fieldsInUse_zgensym_e3caedb3b7ec15ca_3 := z.fieldsNotEmpty(empty_zgensym_e3caedb3b7ec15ca_2[:])

	// map header
	err = en.WriteMapHeader(fieldsInUse_zgensym_e3caedb3b7ec15ca_3 + 1)
	if err != nil {
		return err
	}

	// runtime struct type identification for 'Auction'
	err = en.Append(0xa1, 0x40)
	if err != nil {
		return err
	}
	err = en.WriteStringFromBytes([]byte{0x41, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e})
	if err != nil {
		return err
	}

	if !empty_zgensym_e3caedb3b7ec15ca_2[0] {
		// write "id_zid00_u64"
		err = en.Append(0xac, 0x69, 0x64, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x30, 0x5f, 0x75, 0x36, 0x34)
		if err != nil {
			return err
		}
		err = en.WriteUint64(z.ID)
		if err != nil {
			return
		}
	}

	if !empty_zgensym_e3caedb3b7ec15ca_2[1] {
		// write "itemName_zid01_str"
		err = en.Append(0xb2, 0x69, 0x74, 0x65, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x31, 0x5f, 0x73, 0x74, 0x72)
		if err != nil {
			return err
		}
		err = en.WriteString(z.ItemName)
		if err != nil {
			return
		}
	}

	if !empty_zgensym_e3caedb3b7ec15ca_2[2] {
		// write "description_zid02_str"
		err = en.Append(0xb5, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x32, 0x5f, 0x73, 0x74, 0x72)
		if err != nil {
			return err
		}
		err = en.WriteString(z.Description)
		if err != nil {
			return
		}
	}

	if !empty_zgensym_e3caedb3b7ec15ca_2[3] {
		// write "initialBid_zid03_u64"
		err = en.Append(0xb4, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x42, 0x69, 0x64, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x33, 0x5f, 0x75, 0x36, 0x34)
		if err != nil {
			return err
		}
		err = en.WriteUint64(z.InitialBid)
		if err != nil {
			return
		}
	}

	if !empty_zgensym_e3caedb3b7ec15ca_2[4] {
		// write "reserve_zid04_u64"
		err = en.Append(0xb1, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x34, 0x5f, 0x75, 0x36, 0x34)
		if err != nil {
			return err
		}
		err = en.WriteUint64(z.Reserve)
		if err != nil {
			return
		}
	}

	if !empty_zgensym_e3caedb3b7ec15ca_2[5] {
		// write "dataTime_zid05_i64"
		err = en.Append(0xb2, 0x64, 0x61, 0x74, 0x61, 0x54, 0x69, 0x6d, 0x65, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x35, 0x5f, 0x69, 0x36, 0x34)
		if err != nil {
			return err
		}
		err = en.WriteInt64(z.DateTime)
		if err != nil {
			return
		}
	}

	if !empty_zgensym_e3caedb3b7ec15ca_2[6] {
		// write "expires_zid06_i64"
		err = en.Append(0xb1, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x73, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x36, 0x5f, 0x69, 0x36, 0x34)
		if err != nil {
			return err
		}
		err = en.WriteInt64(z.Expires)
		if err != nil {
			return
		}
	}

	if !empty_zgensym_e3caedb3b7ec15ca_2[7] {
		// write "seller_zid07_u64"
		err = en.Append(0xb0, 0x73, 0x65, 0x6c, 0x6c, 0x65, 0x72, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x37, 0x5f, 0x75, 0x36, 0x34)
		if err != nil {
			return err
		}
		err = en.WriteUint64(z.Seller)
		if err != nil {
			return
		}
	}

	if !empty_zgensym_e3caedb3b7ec15ca_2[8] {
		// write "category_zid08_u64"
		err = en.Append(0xb2, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x38, 0x5f, 0x75, 0x36, 0x34)
		if err != nil {
			return err
		}
		err = en.WriteUint64(z.Category)
		if err != nil {
			return
		}
	}

	if !empty_zgensym_e3caedb3b7ec15ca_2[9] {
		// write "extra_zid09_str"
		err = en.Append(0xaf, 0x65, 0x78, 0x74, 0x72, 0x61, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x39, 0x5f, 0x73, 0x74, 0x72)
		if err != nil {
			return err
		}
		err = en.WriteString(z.Extra)
		if err != nil {
			return
		}
	}

	return
}

// MarshalMsg implements msgp.Marshaler
func (z *Auction) MarshalMsg(b []byte) (o []byte, err error) {
	if p, ok := interface{}(z).(msgp.PreSave); ok {
		p.PreSaveHook()
	}

	o = msgp.Require(b, z.Msgsize())

	// honor the omitempty tags
	var empty [10]bool
	fieldsInUse := z.fieldsNotEmpty(empty[:])
	o = msgp.AppendMapHeader(o, fieldsInUse)

	if !empty[0] {
		// string "id_zid00_u64"
		o = append(o, 0xac, 0x69, 0x64, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x30, 0x5f, 0x75, 0x36, 0x34)
		o = msgp.AppendUint64(o, z.ID)
	}

	if !empty[1] {
		// string "itemName_zid01_str"
		o = append(o, 0xb2, 0x69, 0x74, 0x65, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x31, 0x5f, 0x73, 0x74, 0x72)
		o = msgp.AppendString(o, z.ItemName)
	}

	if !empty[2] {
		// string "description_zid02_str"
		o = append(o, 0xb5, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x32, 0x5f, 0x73, 0x74, 0x72)
		o = msgp.AppendString(o, z.Description)
	}

	if !empty[3] {
		// string "initialBid_zid03_u64"
		o = append(o, 0xb4, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x42, 0x69, 0x64, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x33, 0x5f, 0x75, 0x36, 0x34)
		o = msgp.AppendUint64(o, z.InitialBid)
	}

	if !empty[4] {
		// string "reserve_zid04_u64"
		o = append(o, 0xb1, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x34, 0x5f, 0x75, 0x36, 0x34)
		o = msgp.AppendUint64(o, z.Reserve)
	}

	if !empty[5] {
		// string "dataTime_zid05_i64"
		o = append(o, 0xb2, 0x64, 0x61, 0x74, 0x61, 0x54, 0x69, 0x6d, 0x65, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x35, 0x5f, 0x69, 0x36, 0x34)
		o = msgp.AppendInt64(o, z.DateTime)
	}

	if !empty[6] {
		// string "expires_zid06_i64"
		o = append(o, 0xb1, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x73, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x36, 0x5f, 0x69, 0x36, 0x34)
		o = msgp.AppendInt64(o, z.Expires)
	}

	if !empty[7] {
		// string "seller_zid07_u64"
		o = append(o, 0xb0, 0x73, 0x65, 0x6c, 0x6c, 0x65, 0x72, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x37, 0x5f, 0x75, 0x36, 0x34)
		o = msgp.AppendUint64(o, z.Seller)
	}

	if !empty[8] {
		// string "category_zid08_u64"
		o = append(o, 0xb2, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x38, 0x5f, 0x75, 0x36, 0x34)
		o = msgp.AppendUint64(o, z.Category)
	}

	if !empty[9] {
		// string "extra_zid09_str"
		o = append(o, 0xaf, 0x65, 0x78, 0x74, 0x72, 0x61, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x39, 0x5f, 0x73, 0x74, 0x72)
		o = msgp.AppendString(o, z.Extra)
	}

	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Auction) UnmarshalMsg(bts []byte) (o []byte, err error) {
	return z.UnmarshalMsgWithCfg(bts, nil)
}
func (z *Auction) UnmarshalMsgWithCfg(bts []byte, cfg *msgp.RuntimeConfig) (o []byte, err error) {
	var nbs msgp.NilBitsStack
	nbs.Init(cfg)
	var sawTopNil bool
	if msgp.IsNil(bts) {
		sawTopNil = true
		bts = nbs.PushAlwaysNil(bts[1:])
	}

	var field []byte
	_ = field
	const maxFields4zgensym_e3caedb3b7ec15ca_5 = 10

	// -- templateUnmarshalMsg starts here--
	var totalEncodedFields4zgensym_e3caedb3b7ec15ca_5 uint32
	if !nbs.AlwaysNil {
		totalEncodedFields4zgensym_e3caedb3b7ec15ca_5, bts, err = nbs.ReadMapHeaderBytes(bts)
		if err != nil {
			return
		}
	}
	encodedFieldsLeft4zgensym_e3caedb3b7ec15ca_5 := totalEncodedFields4zgensym_e3caedb3b7ec15ca_5
	missingFieldsLeft4zgensym_e3caedb3b7ec15ca_5 := maxFields4zgensym_e3caedb3b7ec15ca_5 - totalEncodedFields4zgensym_e3caedb3b7ec15ca_5

	var nextMiss4zgensym_e3caedb3b7ec15ca_5 int32 = -1
	var found4zgensym_e3caedb3b7ec15ca_5 [maxFields4zgensym_e3caedb3b7ec15ca_5]bool
	var curField4zgensym_e3caedb3b7ec15ca_5 string

doneWithStruct4zgensym_e3caedb3b7ec15ca_5:
	// First fill all the encoded fields, then
	// treat the remaining, missing fields, as Nil.
	for encodedFieldsLeft4zgensym_e3caedb3b7ec15ca_5 > 0 || missingFieldsLeft4zgensym_e3caedb3b7ec15ca_5 > 0 {
		//fmt.Printf("encodedFieldsLeft: %v, missingFieldsLeft: %v, found: '%v', fields: '%#v'\n", encodedFieldsLeft4zgensym_e3caedb3b7ec15ca_5, missingFieldsLeft4zgensym_e3caedb3b7ec15ca_5, msgp.ShowFound(found4zgensym_e3caedb3b7ec15ca_5[:]), unmarshalMsgFieldOrder4zgensym_e3caedb3b7ec15ca_5)
		if encodedFieldsLeft4zgensym_e3caedb3b7ec15ca_5 > 0 {
			encodedFieldsLeft4zgensym_e3caedb3b7ec15ca_5--
			field, bts, err = nbs.ReadMapKeyZC(bts)
			if err != nil {
				return
			}
			curField4zgensym_e3caedb3b7ec15ca_5 = msgp.UnsafeString(field)
		} else {
			//missing fields need handling
			if nextMiss4zgensym_e3caedb3b7ec15ca_5 < 0 {
				// set bts to contain just mnil (0xc0)
				bts = nbs.PushAlwaysNil(bts)
				nextMiss4zgensym_e3caedb3b7ec15ca_5 = 0
			}
			for nextMiss4zgensym_e3caedb3b7ec15ca_5 < maxFields4zgensym_e3caedb3b7ec15ca_5 && (found4zgensym_e3caedb3b7ec15ca_5[nextMiss4zgensym_e3caedb3b7ec15ca_5] || unmarshalMsgFieldSkip4zgensym_e3caedb3b7ec15ca_5[nextMiss4zgensym_e3caedb3b7ec15ca_5]) {
				nextMiss4zgensym_e3caedb3b7ec15ca_5++
			}
			if nextMiss4zgensym_e3caedb3b7ec15ca_5 == maxFields4zgensym_e3caedb3b7ec15ca_5 {
				// filled all the empty fields!
				break doneWithStruct4zgensym_e3caedb3b7ec15ca_5
			}
			missingFieldsLeft4zgensym_e3caedb3b7ec15ca_5--
			curField4zgensym_e3caedb3b7ec15ca_5 = unmarshalMsgFieldOrder4zgensym_e3caedb3b7ec15ca_5[nextMiss4zgensym_e3caedb3b7ec15ca_5]
		}
		//fmt.Printf("switching on curField: '%v'\n", curField4zgensym_e3caedb3b7ec15ca_5)
		switch curField4zgensym_e3caedb3b7ec15ca_5 {
		// -- templateUnmarshalMsg ends here --

		case "id_zid00_u64":
			found4zgensym_e3caedb3b7ec15ca_5[0] = true
			z.ID, bts, err = nbs.ReadUint64Bytes(bts)

			if err != nil {
				return
			}
		case "itemName_zid01_str":
			found4zgensym_e3caedb3b7ec15ca_5[1] = true
			z.ItemName, bts, err = nbs.ReadStringBytes(bts)

			if err != nil {
				return
			}
		case "description_zid02_str":
			found4zgensym_e3caedb3b7ec15ca_5[2] = true
			z.Description, bts, err = nbs.ReadStringBytes(bts)

			if err != nil {
				return
			}
		case "initialBid_zid03_u64":
			found4zgensym_e3caedb3b7ec15ca_5[3] = true
			z.InitialBid, bts, err = nbs.ReadUint64Bytes(bts)

			if err != nil {
				return
			}
		case "reserve_zid04_u64":
			found4zgensym_e3caedb3b7ec15ca_5[4] = true
			z.Reserve, bts, err = nbs.ReadUint64Bytes(bts)

			if err != nil {
				return
			}
		case "dataTime_zid05_i64":
			found4zgensym_e3caedb3b7ec15ca_5[5] = true
			z.DateTime, bts, err = nbs.ReadInt64Bytes(bts)

			if err != nil {
				return
			}
		case "expires_zid06_i64":
			found4zgensym_e3caedb3b7ec15ca_5[6] = true
			z.Expires, bts, err = nbs.ReadInt64Bytes(bts)

			if err != nil {
				return
			}
		case "seller_zid07_u64":
			found4zgensym_e3caedb3b7ec15ca_5[7] = true
			z.Seller, bts, err = nbs.ReadUint64Bytes(bts)

			if err != nil {
				return
			}
		case "category_zid08_u64":
			found4zgensym_e3caedb3b7ec15ca_5[8] = true
			z.Category, bts, err = nbs.ReadUint64Bytes(bts)

			if err != nil {
				return
			}
		case "extra_zid09_str":
			found4zgensym_e3caedb3b7ec15ca_5[9] = true
			z.Extra, bts, err = nbs.ReadStringBytes(bts)

			if err != nil {
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				return
			}
		}
	}
	if nextMiss4zgensym_e3caedb3b7ec15ca_5 != -1 {
		bts = nbs.PopAlwaysNil()
	}

	if sawTopNil {
		bts = nbs.PopAlwaysNil()
	}
	o = bts
	if p, ok := interface{}(z).(msgp.PostLoad); ok {
		p.PostLoadHook()
	}

	return
}

// fields of Auction
var unmarshalMsgFieldOrder4zgensym_e3caedb3b7ec15ca_5 = []string{"id_zid00_u64", "itemName_zid01_str", "description_zid02_str", "initialBid_zid03_u64", "reserve_zid04_u64", "dataTime_zid05_i64", "expires_zid06_i64", "seller_zid07_u64", "category_zid08_u64", "extra_zid09_str"}

var unmarshalMsgFieldSkip4zgensym_e3caedb3b7ec15ca_5 = []bool{false, false, false, false, false, false, false, false, false, false}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *Auction) Msgsize() (s int) {
	s = 1 + 13 + msgp.Uint64Size + 19 + msgp.StringPrefixSize + len(z.ItemName) + 22 + msgp.StringPrefixSize + len(z.Description) + 21 + msgp.Uint64Size + 18 + msgp.Uint64Size + 19 + msgp.Int64Size + 18 + msgp.Int64Size + 17 + msgp.Uint64Size + 19 + msgp.Uint64Size + 16 + msgp.StringPrefixSize + len(z.Extra)
	return
}

// DecodeMsg implements msgp.Decodable
// We treat empty fields as if we read a Nil from the wire.
func (z *Bid) DecodeMsg(dc *msgp.Reader) (err error) {
	var sawTopNil bool
	if dc.IsNil() {
		sawTopNil = true
		err = dc.ReadNil()
		if err != nil {
			return
		}
		dc.PushAlwaysNil()
	}

	var field []byte
	_ = field
	const maxFields6zgensym_e3caedb3b7ec15ca_7 = 7

	// -- templateDecodeMsg starts here--
	var totalEncodedFields6zgensym_e3caedb3b7ec15ca_7 uint32
	totalEncodedFields6zgensym_e3caedb3b7ec15ca_7, err = dc.ReadMapHeader()
	if err != nil {
		return
	}
	encodedFieldsLeft6zgensym_e3caedb3b7ec15ca_7 := totalEncodedFields6zgensym_e3caedb3b7ec15ca_7
	missingFieldsLeft6zgensym_e3caedb3b7ec15ca_7 := maxFields6zgensym_e3caedb3b7ec15ca_7 - totalEncodedFields6zgensym_e3caedb3b7ec15ca_7

	var nextMiss6zgensym_e3caedb3b7ec15ca_7 int32 = -1
	var found6zgensym_e3caedb3b7ec15ca_7 [maxFields6zgensym_e3caedb3b7ec15ca_7]bool
	var curField6zgensym_e3caedb3b7ec15ca_7 string

doneWithStruct6zgensym_e3caedb3b7ec15ca_7:
	// First fill all the encoded fields, then
	// treat the remaining, missing fields, as Nil.
	for encodedFieldsLeft6zgensym_e3caedb3b7ec15ca_7 > 0 || missingFieldsLeft6zgensym_e3caedb3b7ec15ca_7 > 0 {
		//fmt.Printf("encodedFieldsLeft: %v, missingFieldsLeft: %v, found: '%v', fields: '%#v'\n", encodedFieldsLeft6zgensym_e3caedb3b7ec15ca_7, missingFieldsLeft6zgensym_e3caedb3b7ec15ca_7, msgp.ShowFound(found6zgensym_e3caedb3b7ec15ca_7[:]), decodeMsgFieldOrder6zgensym_e3caedb3b7ec15ca_7)
		if encodedFieldsLeft6zgensym_e3caedb3b7ec15ca_7 > 0 {
			encodedFieldsLeft6zgensym_e3caedb3b7ec15ca_7--
			field, err = dc.ReadMapKeyPtr()
			if err != nil {
				return
			}
			curField6zgensym_e3caedb3b7ec15ca_7 = msgp.UnsafeString(field)
		} else {
			//missing fields need handling
			if nextMiss6zgensym_e3caedb3b7ec15ca_7 < 0 {
				// tell the reader to only give us Nils
				// until further notice.
				dc.PushAlwaysNil()
				nextMiss6zgensym_e3caedb3b7ec15ca_7 = 0
			}
			for nextMiss6zgensym_e3caedb3b7ec15ca_7 < maxFields6zgensym_e3caedb3b7ec15ca_7 && (found6zgensym_e3caedb3b7ec15ca_7[nextMiss6zgensym_e3caedb3b7ec15ca_7] || decodeMsgFieldSkip6zgensym_e3caedb3b7ec15ca_7[nextMiss6zgensym_e3caedb3b7ec15ca_7]) {
				nextMiss6zgensym_e3caedb3b7ec15ca_7++
			}
			if nextMiss6zgensym_e3caedb3b7ec15ca_7 == maxFields6zgensym_e3caedb3b7ec15ca_7 {
				// filled all the empty fields!
				break doneWithStruct6zgensym_e3caedb3b7ec15ca_7
			}
			missingFieldsLeft6zgensym_e3caedb3b7ec15ca_7--
			curField6zgensym_e3caedb3b7ec15ca_7 = decodeMsgFieldOrder6zgensym_e3caedb3b7ec15ca_7[nextMiss6zgensym_e3caedb3b7ec15ca_7]
		}
		//fmt.Printf("switching on curField: '%v'\n", curField6zgensym_e3caedb3b7ec15ca_7)
		switch curField6zgensym_e3caedb3b7ec15ca_7 {
		// -- templateDecodeMsg ends here --

		case "auction_zid00_u64":
			found6zgensym_e3caedb3b7ec15ca_7[0] = true
			z.Auction, err = dc.ReadUint64()
			if err != nil {
				return
			}
		case "bidder_zid01_u64":
			found6zgensym_e3caedb3b7ec15ca_7[1] = true
			z.Bidder, err = dc.ReadUint64()
			if err != nil {
				return
			}
		case "price_zid02_u64":
			found6zgensym_e3caedb3b7ec15ca_7[2] = true
			z.Price, err = dc.ReadUint64()
			if err != nil {
				return
			}
		case "channel_zid03_str":
			found6zgensym_e3caedb3b7ec15ca_7[3] = true
			z.Channel, err = dc.ReadString()
			if err != nil {
				return
			}
		case "url_zid04_str":
			found6zgensym_e3caedb3b7ec15ca_7[4] = true
			z.Url, err = dc.ReadString()
			if err != nil {
				return
			}
		case "dateTime_zid05_i64":
			found6zgensym_e3caedb3b7ec15ca_7[5] = true
			z.DateTime, err = dc.ReadInt64()
			if err != nil {
				return
			}
		case "extra_zid06_str":
			found6zgensym_e3caedb3b7ec15ca_7[6] = true
			z.Extra, err = dc.ReadString()
			if err != nil {
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				return
			}
		}
	}
	if nextMiss6zgensym_e3caedb3b7ec15ca_7 != -1 {
		dc.PopAlwaysNil()
	}

	if sawTopNil {
		dc.PopAlwaysNil()
	}

	if p, ok := interface{}(z).(msgp.PostLoad); ok {
		p.PostLoadHook()
	}

	return
}

// fields of Bid
var decodeMsgFieldOrder6zgensym_e3caedb3b7ec15ca_7 = []string{"auction_zid00_u64", "bidder_zid01_u64", "price_zid02_u64", "channel_zid03_str", "url_zid04_str", "dateTime_zid05_i64", "extra_zid06_str"}

var decodeMsgFieldSkip6zgensym_e3caedb3b7ec15ca_7 = []bool{false, false, false, false, false, false, false}

// fieldsNotEmpty supports omitempty tags
func (z *Bid) fieldsNotEmpty(isempty []bool) uint32 {
	if len(isempty) == 0 {
		return 7
	}
	var fieldsInUse uint32 = 7
	isempty[0] = (z.Auction == 0) // number, omitempty
	if isempty[0] {
		fieldsInUse--
	}
	isempty[1] = (z.Bidder == 0) // number, omitempty
	if isempty[1] {
		fieldsInUse--
	}
	isempty[2] = (z.Price == 0) // number, omitempty
	if isempty[2] {
		fieldsInUse--
	}
	isempty[3] = (len(z.Channel) == 0) // string, omitempty
	if isempty[3] {
		fieldsInUse--
	}
	isempty[4] = (len(z.Url) == 0) // string, omitempty
	if isempty[4] {
		fieldsInUse--
	}
	isempty[5] = (z.DateTime == 0) // number, omitempty
	if isempty[5] {
		fieldsInUse--
	}
	isempty[6] = (len(z.Extra) == 0) // string, omitempty
	if isempty[6] {
		fieldsInUse--
	}

	return fieldsInUse
}

// EncodeMsg implements msgp.Encodable
func (z *Bid) EncodeMsg(en *msgp.Writer) (err error) {
	if p, ok := interface{}(z).(msgp.PreSave); ok {
		p.PreSaveHook()
	}

	// honor the omitempty tags
	var empty_zgensym_e3caedb3b7ec15ca_8 [7]bool
	fieldsInUse_zgensym_e3caedb3b7ec15ca_9 := z.fieldsNotEmpty(empty_zgensym_e3caedb3b7ec15ca_8[:])

	// map header
	err = en.WriteMapHeader(fieldsInUse_zgensym_e3caedb3b7ec15ca_9 + 1)
	if err != nil {
		return err
	}

	// runtime struct type identification for 'Bid'
	err = en.Append(0xa1, 0x40)
	if err != nil {
		return err
	}
	err = en.WriteStringFromBytes([]byte{0x42, 0x69, 0x64})
	if err != nil {
		return err
	}

	if !empty_zgensym_e3caedb3b7ec15ca_8[0] {
		// write "auction_zid00_u64"
		err = en.Append(0xb1, 0x61, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x30, 0x5f, 0x75, 0x36, 0x34)
		if err != nil {
			return err
		}
		err = en.WriteUint64(z.Auction)
		if err != nil {
			return
		}
	}

	if !empty_zgensym_e3caedb3b7ec15ca_8[1] {
		// write "bidder_zid01_u64"
		err = en.Append(0xb0, 0x62, 0x69, 0x64, 0x64, 0x65, 0x72, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x31, 0x5f, 0x75, 0x36, 0x34)
		if err != nil {
			return err
		}
		err = en.WriteUint64(z.Bidder)
		if err != nil {
			return
		}
	}

	if !empty_zgensym_e3caedb3b7ec15ca_8[2] {
		// write "price_zid02_u64"
		err = en.Append(0xaf, 0x70, 0x72, 0x69, 0x63, 0x65, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x32, 0x5f, 0x75, 0x36, 0x34)
		if err != nil {
			return err
		}
		err = en.WriteUint64(z.Price)
		if err != nil {
			return
		}
	}

	if !empty_zgensym_e3caedb3b7ec15ca_8[3] {
		// write "channel_zid03_str"
		err = en.Append(0xb1, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x33, 0x5f, 0x73, 0x74, 0x72)
		if err != nil {
			return err
		}
		err = en.WriteString(z.Channel)
		if err != nil {
			return
		}
	}

	if !empty_zgensym_e3caedb3b7ec15ca_8[4] {
		// write "url_zid04_str"
		err = en.Append(0xad, 0x75, 0x72, 0x6c, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x34, 0x5f, 0x73, 0x74, 0x72)
		if err != nil {
			return err
		}
		err = en.WriteString(z.Url)
		if err != nil {
			return
		}
	}

	if !empty_zgensym_e3caedb3b7ec15ca_8[5] {
		// write "dateTime_zid05_i64"
		err = en.Append(0xb2, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x35, 0x5f, 0x69, 0x36, 0x34)
		if err != nil {
			return err
		}
		err = en.WriteInt64(z.DateTime)
		if err != nil {
			return
		}
	}

	if !empty_zgensym_e3caedb3b7ec15ca_8[6] {
		// write "extra_zid06_str"
		err = en.Append(0xaf, 0x65, 0x78, 0x74, 0x72, 0x61, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x36, 0x5f, 0x73, 0x74, 0x72)
		if err != nil {
			return err
		}
		err = en.WriteString(z.Extra)
		if err != nil {
			return
		}
	}

	return
}

// MarshalMsg implements msgp.Marshaler
func (z *Bid) MarshalMsg(b []byte) (o []byte, err error) {
	if p, ok := interface{}(z).(msgp.PreSave); ok {
		p.PreSaveHook()
	}

	o = msgp.Require(b, z.Msgsize())

	// honor the omitempty tags
	var empty [7]bool
	fieldsInUse := z.fieldsNotEmpty(empty[:])
	o = msgp.AppendMapHeader(o, fieldsInUse)

	if !empty[0] {
		// string "auction_zid00_u64"
		o = append(o, 0xb1, 0x61, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x30, 0x5f, 0x75, 0x36, 0x34)
		o = msgp.AppendUint64(o, z.Auction)
	}

	if !empty[1] {
		// string "bidder_zid01_u64"
		o = append(o, 0xb0, 0x62, 0x69, 0x64, 0x64, 0x65, 0x72, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x31, 0x5f, 0x75, 0x36, 0x34)
		o = msgp.AppendUint64(o, z.Bidder)
	}

	if !empty[2] {
		// string "price_zid02_u64"
		o = append(o, 0xaf, 0x70, 0x72, 0x69, 0x63, 0x65, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x32, 0x5f, 0x75, 0x36, 0x34)
		o = msgp.AppendUint64(o, z.Price)
	}

	if !empty[3] {
		// string "channel_zid03_str"
		o = append(o, 0xb1, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x33, 0x5f, 0x73, 0x74, 0x72)
		o = msgp.AppendString(o, z.Channel)
	}

	if !empty[4] {
		// string "url_zid04_str"
		o = append(o, 0xad, 0x75, 0x72, 0x6c, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x34, 0x5f, 0x73, 0x74, 0x72)
		o = msgp.AppendString(o, z.Url)
	}

	if !empty[5] {
		// string "dateTime_zid05_i64"
		o = append(o, 0xb2, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x35, 0x5f, 0x69, 0x36, 0x34)
		o = msgp.AppendInt64(o, z.DateTime)
	}

	if !empty[6] {
		// string "extra_zid06_str"
		o = append(o, 0xaf, 0x65, 0x78, 0x74, 0x72, 0x61, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x36, 0x5f, 0x73, 0x74, 0x72)
		o = msgp.AppendString(o, z.Extra)
	}

	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Bid) UnmarshalMsg(bts []byte) (o []byte, err error) {
	return z.UnmarshalMsgWithCfg(bts, nil)
}
func (z *Bid) UnmarshalMsgWithCfg(bts []byte, cfg *msgp.RuntimeConfig) (o []byte, err error) {
	var nbs msgp.NilBitsStack
	nbs.Init(cfg)
	var sawTopNil bool
	if msgp.IsNil(bts) {
		sawTopNil = true
		bts = nbs.PushAlwaysNil(bts[1:])
	}

	var field []byte
	_ = field
	const maxFields10zgensym_e3caedb3b7ec15ca_11 = 7

	// -- templateUnmarshalMsg starts here--
	var totalEncodedFields10zgensym_e3caedb3b7ec15ca_11 uint32
	if !nbs.AlwaysNil {
		totalEncodedFields10zgensym_e3caedb3b7ec15ca_11, bts, err = nbs.ReadMapHeaderBytes(bts)
		if err != nil {
			return
		}
	}
	encodedFieldsLeft10zgensym_e3caedb3b7ec15ca_11 := totalEncodedFields10zgensym_e3caedb3b7ec15ca_11
	missingFieldsLeft10zgensym_e3caedb3b7ec15ca_11 := maxFields10zgensym_e3caedb3b7ec15ca_11 - totalEncodedFields10zgensym_e3caedb3b7ec15ca_11

	var nextMiss10zgensym_e3caedb3b7ec15ca_11 int32 = -1
	var found10zgensym_e3caedb3b7ec15ca_11 [maxFields10zgensym_e3caedb3b7ec15ca_11]bool
	var curField10zgensym_e3caedb3b7ec15ca_11 string

doneWithStruct10zgensym_e3caedb3b7ec15ca_11:
	// First fill all the encoded fields, then
	// treat the remaining, missing fields, as Nil.
	for encodedFieldsLeft10zgensym_e3caedb3b7ec15ca_11 > 0 || missingFieldsLeft10zgensym_e3caedb3b7ec15ca_11 > 0 {
		//fmt.Printf("encodedFieldsLeft: %v, missingFieldsLeft: %v, found: '%v', fields: '%#v'\n", encodedFieldsLeft10zgensym_e3caedb3b7ec15ca_11, missingFieldsLeft10zgensym_e3caedb3b7ec15ca_11, msgp.ShowFound(found10zgensym_e3caedb3b7ec15ca_11[:]), unmarshalMsgFieldOrder10zgensym_e3caedb3b7ec15ca_11)
		if encodedFieldsLeft10zgensym_e3caedb3b7ec15ca_11 > 0 {
			encodedFieldsLeft10zgensym_e3caedb3b7ec15ca_11--
			field, bts, err = nbs.ReadMapKeyZC(bts)
			if err != nil {
				return
			}
			curField10zgensym_e3caedb3b7ec15ca_11 = msgp.UnsafeString(field)
		} else {
			//missing fields need handling
			if nextMiss10zgensym_e3caedb3b7ec15ca_11 < 0 {
				// set bts to contain just mnil (0xc0)
				bts = nbs.PushAlwaysNil(bts)
				nextMiss10zgensym_e3caedb3b7ec15ca_11 = 0
			}
			for nextMiss10zgensym_e3caedb3b7ec15ca_11 < maxFields10zgensym_e3caedb3b7ec15ca_11 && (found10zgensym_e3caedb3b7ec15ca_11[nextMiss10zgensym_e3caedb3b7ec15ca_11] || unmarshalMsgFieldSkip10zgensym_e3caedb3b7ec15ca_11[nextMiss10zgensym_e3caedb3b7ec15ca_11]) {
				nextMiss10zgensym_e3caedb3b7ec15ca_11++
			}
			if nextMiss10zgensym_e3caedb3b7ec15ca_11 == maxFields10zgensym_e3caedb3b7ec15ca_11 {
				// filled all the empty fields!
				break doneWithStruct10zgensym_e3caedb3b7ec15ca_11
			}
			missingFieldsLeft10zgensym_e3caedb3b7ec15ca_11--
			curField10zgensym_e3caedb3b7ec15ca_11 = unmarshalMsgFieldOrder10zgensym_e3caedb3b7ec15ca_11[nextMiss10zgensym_e3caedb3b7ec15ca_11]
		}
		//fmt.Printf("switching on curField: '%v'\n", curField10zgensym_e3caedb3b7ec15ca_11)
		switch curField10zgensym_e3caedb3b7ec15ca_11 {
		// -- templateUnmarshalMsg ends here --

		case "auction_zid00_u64":
			found10zgensym_e3caedb3b7ec15ca_11[0] = true
			z.Auction, bts, err = nbs.ReadUint64Bytes(bts)

			if err != nil {
				return
			}
		case "bidder_zid01_u64":
			found10zgensym_e3caedb3b7ec15ca_11[1] = true
			z.Bidder, bts, err = nbs.ReadUint64Bytes(bts)

			if err != nil {
				return
			}
		case "price_zid02_u64":
			found10zgensym_e3caedb3b7ec15ca_11[2] = true
			z.Price, bts, err = nbs.ReadUint64Bytes(bts)

			if err != nil {
				return
			}
		case "channel_zid03_str":
			found10zgensym_e3caedb3b7ec15ca_11[3] = true
			z.Channel, bts, err = nbs.ReadStringBytes(bts)

			if err != nil {
				return
			}
		case "url_zid04_str":
			found10zgensym_e3caedb3b7ec15ca_11[4] = true
			z.Url, bts, err = nbs.ReadStringBytes(bts)

			if err != nil {
				return
			}
		case "dateTime_zid05_i64":
			found10zgensym_e3caedb3b7ec15ca_11[5] = true
			z.DateTime, bts, err = nbs.ReadInt64Bytes(bts)

			if err != nil {
				return
			}
		case "extra_zid06_str":
			found10zgensym_e3caedb3b7ec15ca_11[6] = true
			z.Extra, bts, err = nbs.ReadStringBytes(bts)

			if err != nil {
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				return
			}
		}
	}
	if nextMiss10zgensym_e3caedb3b7ec15ca_11 != -1 {
		bts = nbs.PopAlwaysNil()
	}

	if sawTopNil {
		bts = nbs.PopAlwaysNil()
	}
	o = bts
	if p, ok := interface{}(z).(msgp.PostLoad); ok {
		p.PostLoadHook()
	}

	return
}

// fields of Bid
var unmarshalMsgFieldOrder10zgensym_e3caedb3b7ec15ca_11 = []string{"auction_zid00_u64", "bidder_zid01_u64", "price_zid02_u64", "channel_zid03_str", "url_zid04_str", "dateTime_zid05_i64", "extra_zid06_str"}

var unmarshalMsgFieldSkip10zgensym_e3caedb3b7ec15ca_11 = []bool{false, false, false, false, false, false, false}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *Bid) Msgsize() (s int) {
	s = 1 + 18 + msgp.Uint64Size + 17 + msgp.Uint64Size + 16 + msgp.Uint64Size + 18 + msgp.StringPrefixSize + len(z.Channel) + 14 + msgp.StringPrefixSize + len(z.Url) + 19 + msgp.Int64Size + 16 + msgp.StringPrefixSize + len(z.Extra)
	return
}

// DecodeMsg implements msgp.Decodable
// We treat empty fields as if we read a Nil from the wire.
func (z *EType) DecodeMsg(dc *msgp.Reader) (err error) {
	var sawTopNil bool
	if dc.IsNil() {
		sawTopNil = true
		err = dc.ReadNil()
		if err != nil {
			return
		}
		dc.PushAlwaysNil()
	}

	{
		var zgensym_e3caedb3b7ec15ca_12 uint8
		zgensym_e3caedb3b7ec15ca_12, err = dc.ReadUint8()
		(*z) = EType(zgensym_e3caedb3b7ec15ca_12)
	}
	if err != nil {
		return
	}
	if sawTopNil {
		dc.PopAlwaysNil()
	}

	if p, ok := interface{}(z).(msgp.PostLoad); ok {
		p.PostLoadHook()
	}

	return
}

// EncodeMsg implements msgp.Encodable
func (z EType) EncodeMsg(en *msgp.Writer) (err error) {
	if p, ok := interface{}(z).(msgp.PreSave); ok {
		p.PreSaveHook()
	}

	err = en.WriteUint8(uint8(z))
	if err != nil {
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z EType) MarshalMsg(b []byte) (o []byte, err error) {
	if p, ok := interface{}(z).(msgp.PreSave); ok {
		p.PreSaveHook()
	}

	o = msgp.Require(b, z.Msgsize())
	o = msgp.AppendUint8(o, uint8(z))
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *EType) UnmarshalMsg(bts []byte) (o []byte, err error) {
	return z.UnmarshalMsgWithCfg(bts, nil)
}
func (z *EType) UnmarshalMsgWithCfg(bts []byte, cfg *msgp.RuntimeConfig) (o []byte, err error) {
	var nbs msgp.NilBitsStack
	nbs.Init(cfg)
	var sawTopNil bool
	if msgp.IsNil(bts) {
		sawTopNil = true
		bts = nbs.PushAlwaysNil(bts[1:])
	}

	{
		var zgensym_e3caedb3b7ec15ca_13 uint8
		zgensym_e3caedb3b7ec15ca_13, bts, err = nbs.ReadUint8Bytes(bts)

		if err != nil {
			return
		}
		(*z) = EType(zgensym_e3caedb3b7ec15ca_13)
	}
	if sawTopNil {
		bts = nbs.PopAlwaysNil()
	}
	o = bts
	if p, ok := interface{}(z).(msgp.PostLoad); ok {
		p.PostLoadHook()
	}

	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z EType) Msgsize() (s int) {
	s = msgp.Uint8Size
	return
}

// DecodeMsg implements msgp.Decodable
// We treat empty fields as if we read a Nil from the wire.
func (z *Event) DecodeMsg(dc *msgp.Reader) (err error) {
	var sawTopNil bool
	if dc.IsNil() {
		sawTopNil = true
		err = dc.ReadNil()
		if err != nil {
			return
		}
		dc.PushAlwaysNil()
	}

	var field []byte
	_ = field
	const maxFields14zgensym_e3caedb3b7ec15ca_15 = 4

	// -- templateDecodeMsg starts here--
	var totalEncodedFields14zgensym_e3caedb3b7ec15ca_15 uint32
	totalEncodedFields14zgensym_e3caedb3b7ec15ca_15, err = dc.ReadMapHeader()
	if err != nil {
		return
	}
	encodedFieldsLeft14zgensym_e3caedb3b7ec15ca_15 := totalEncodedFields14zgensym_e3caedb3b7ec15ca_15
	missingFieldsLeft14zgensym_e3caedb3b7ec15ca_15 := maxFields14zgensym_e3caedb3b7ec15ca_15 - totalEncodedFields14zgensym_e3caedb3b7ec15ca_15

	var nextMiss14zgensym_e3caedb3b7ec15ca_15 int32 = -1
	var found14zgensym_e3caedb3b7ec15ca_15 [maxFields14zgensym_e3caedb3b7ec15ca_15]bool
	var curField14zgensym_e3caedb3b7ec15ca_15 string

doneWithStruct14zgensym_e3caedb3b7ec15ca_15:
	// First fill all the encoded fields, then
	// treat the remaining, missing fields, as Nil.
	for encodedFieldsLeft14zgensym_e3caedb3b7ec15ca_15 > 0 || missingFieldsLeft14zgensym_e3caedb3b7ec15ca_15 > 0 {
		//fmt.Printf("encodedFieldsLeft: %v, missingFieldsLeft: %v, found: '%v', fields: '%#v'\n", encodedFieldsLeft14zgensym_e3caedb3b7ec15ca_15, missingFieldsLeft14zgensym_e3caedb3b7ec15ca_15, msgp.ShowFound(found14zgensym_e3caedb3b7ec15ca_15[:]), decodeMsgFieldOrder14zgensym_e3caedb3b7ec15ca_15)
		if encodedFieldsLeft14zgensym_e3caedb3b7ec15ca_15 > 0 {
			encodedFieldsLeft14zgensym_e3caedb3b7ec15ca_15--
			field, err = dc.ReadMapKeyPtr()
			if err != nil {
				return
			}
			curField14zgensym_e3caedb3b7ec15ca_15 = msgp.UnsafeString(field)
		} else {
			//missing fields need handling
			if nextMiss14zgensym_e3caedb3b7ec15ca_15 < 0 {
				// tell the reader to only give us Nils
				// until further notice.
				dc.PushAlwaysNil()
				nextMiss14zgensym_e3caedb3b7ec15ca_15 = 0
			}
			for nextMiss14zgensym_e3caedb3b7ec15ca_15 < maxFields14zgensym_e3caedb3b7ec15ca_15 && (found14zgensym_e3caedb3b7ec15ca_15[nextMiss14zgensym_e3caedb3b7ec15ca_15] || decodeMsgFieldSkip14zgensym_e3caedb3b7ec15ca_15[nextMiss14zgensym_e3caedb3b7ec15ca_15]) {
				nextMiss14zgensym_e3caedb3b7ec15ca_15++
			}
			if nextMiss14zgensym_e3caedb3b7ec15ca_15 == maxFields14zgensym_e3caedb3b7ec15ca_15 {
				// filled all the empty fields!
				break doneWithStruct14zgensym_e3caedb3b7ec15ca_15
			}
			missingFieldsLeft14zgensym_e3caedb3b7ec15ca_15--
			curField14zgensym_e3caedb3b7ec15ca_15 = decodeMsgFieldOrder14zgensym_e3caedb3b7ec15ca_15[nextMiss14zgensym_e3caedb3b7ec15ca_15]
		}
		//fmt.Printf("switching on curField: '%v'\n", curField14zgensym_e3caedb3b7ec15ca_15)
		switch curField14zgensym_e3caedb3b7ec15ca_15 {
		// -- templateDecodeMsg ends here --

		case "Etype_zid00_rct":
			found14zgensym_e3caedb3b7ec15ca_15[0] = true
			{
				var zgensym_e3caedb3b7ec15ca_16 uint8
				zgensym_e3caedb3b7ec15ca_16, err = dc.ReadUint8()
				z.Etype = EType(zgensym_e3caedb3b7ec15ca_16)
			}
			if err != nil {
				return
			}
		case "NewPerson_zid01_ptr":
			found14zgensym_e3caedb3b7ec15ca_15[1] = true
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					return
				}

				if z.NewPerson != nil {
					dc.PushAlwaysNil()
					err = z.NewPerson.DecodeMsg(dc)
					if err != nil {
						return
					}
					dc.PopAlwaysNil()
				}
			} else {
				// not Nil, we have something to read

				if z.NewPerson == nil {
					z.NewPerson = new(Person)
				}
				dc.DedupIndexEachPtr(z.NewPerson)

				err = z.NewPerson.DecodeMsg(dc)
				if err != nil {
					return
				}
			}
		case "NewAuction_zid02_ptr":
			found14zgensym_e3caedb3b7ec15ca_15[2] = true
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					return
				}

				if z.NewAuction != nil {
					dc.PushAlwaysNil()
					err = z.NewAuction.DecodeMsg(dc)
					if err != nil {
						return
					}
					dc.PopAlwaysNil()
				}
			} else {
				// not Nil, we have something to read

				if z.NewAuction == nil {
					z.NewAuction = new(Auction)
				}
				dc.DedupIndexEachPtr(z.NewAuction)

				err = z.NewAuction.DecodeMsg(dc)
				if err != nil {
					return
				}
			}
		case "Bid_zid03_ptr":
			found14zgensym_e3caedb3b7ec15ca_15[3] = true
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					return
				}

				if z.Bid != nil {
					dc.PushAlwaysNil()
					err = z.Bid.DecodeMsg(dc)
					if err != nil {
						return
					}
					dc.PopAlwaysNil()
				}
			} else {
				// not Nil, we have something to read

				if z.Bid == nil {
					z.Bid = new(Bid)
				}
				dc.DedupIndexEachPtr(z.Bid)

				err = z.Bid.DecodeMsg(dc)
				if err != nil {
					return
				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				return
			}
		}
	}
	if nextMiss14zgensym_e3caedb3b7ec15ca_15 != -1 {
		dc.PopAlwaysNil()
	}

	if sawTopNil {
		dc.PopAlwaysNil()
	}

	if p, ok := interface{}(z).(msgp.PostLoad); ok {
		p.PostLoadHook()
	}

	return
}

// fields of Event
var decodeMsgFieldOrder14zgensym_e3caedb3b7ec15ca_15 = []string{"Etype_zid00_rct", "NewPerson_zid01_ptr", "NewAuction_zid02_ptr", "Bid_zid03_ptr"}

var decodeMsgFieldSkip14zgensym_e3caedb3b7ec15ca_15 = []bool{false, false, false, false}

// fieldsNotEmpty supports omitempty tags
func (z *Event) fieldsNotEmpty(isempty []bool) uint32 {
	if len(isempty) == 0 {
		return 4
	}
	var fieldsInUse uint32 = 4
	isempty[0] = (z.Etype == 0) // number, omitempty
	if isempty[0] {
		fieldsInUse--
	}
	isempty[1] = (z.NewPerson == nil) // pointer, omitempty
	if isempty[1] {
		fieldsInUse--
	}
	isempty[2] = (z.NewAuction == nil) // pointer, omitempty
	if isempty[2] {
		fieldsInUse--
	}
	isempty[3] = (z.Bid == nil) // pointer, omitempty
	if isempty[3] {
		fieldsInUse--
	}

	return fieldsInUse
}

// EncodeMsg implements msgp.Encodable
func (z *Event) EncodeMsg(en *msgp.Writer) (err error) {
	if p, ok := interface{}(z).(msgp.PreSave); ok {
		p.PreSaveHook()
	}

	// honor the omitempty tags
	var empty_zgensym_e3caedb3b7ec15ca_17 [4]bool
	fieldsInUse_zgensym_e3caedb3b7ec15ca_18 := z.fieldsNotEmpty(empty_zgensym_e3caedb3b7ec15ca_17[:])

	// map header
	err = en.WriteMapHeader(fieldsInUse_zgensym_e3caedb3b7ec15ca_18 + 1)
	if err != nil {
		return err
	}

	// runtime struct type identification for 'Event'
	err = en.Append(0xa1, 0x40)
	if err != nil {
		return err
	}
	err = en.WriteStringFromBytes([]byte{0x45, 0x76, 0x65, 0x6e, 0x74})
	if err != nil {
		return err
	}

	if !empty_zgensym_e3caedb3b7ec15ca_17[0] {
		// write "Etype_zid00_rct"
		err = en.Append(0xaf, 0x45, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x30, 0x5f, 0x72, 0x63, 0x74)
		if err != nil {
			return err
		}
		err = en.WriteUint8(uint8(z.Etype))
		if err != nil {
			return
		}
	}

	if !empty_zgensym_e3caedb3b7ec15ca_17[1] {
		// write "NewPerson_zid01_ptr"
		err = en.Append(0xb3, 0x4e, 0x65, 0x77, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x31, 0x5f, 0x70, 0x74, 0x72)
		if err != nil {
			return err
		}
		// gPtr.encodeGen():

		if z.NewPerson == nil {
			err = en.WriteNil()
			if err != nil {
				return
			}
		} else {
			// encodeGen.gBase IDENT

			// record the interface for deduplication
			var dup bool
			dup, err = en.DedupWriteIsDup(z.NewPerson)
			if err != nil {
				return
			}
			if !dup {
				err = z.NewPerson.EncodeMsg(en)
				if err != nil {
					return
				}
			}
		}
	}

	if !empty_zgensym_e3caedb3b7ec15ca_17[2] {
		// write "NewAuction_zid02_ptr"
		err = en.Append(0xb4, 0x4e, 0x65, 0x77, 0x41, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x32, 0x5f, 0x70, 0x74, 0x72)
		if err != nil {
			return err
		}
		// gPtr.encodeGen():

		if z.NewAuction == nil {
			err = en.WriteNil()
			if err != nil {
				return
			}
		} else {
			// encodeGen.gBase IDENT

			// record the interface for deduplication
			var dup bool
			dup, err = en.DedupWriteIsDup(z.NewAuction)
			if err != nil {
				return
			}
			if !dup {
				err = z.NewAuction.EncodeMsg(en)
				if err != nil {
					return
				}
			}
		}
	}

	if !empty_zgensym_e3caedb3b7ec15ca_17[3] {
		// write "Bid_zid03_ptr"
		err = en.Append(0xad, 0x42, 0x69, 0x64, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x33, 0x5f, 0x70, 0x74, 0x72)
		if err != nil {
			return err
		}
		// gPtr.encodeGen():

		if z.Bid == nil {
			err = en.WriteNil()
			if err != nil {
				return
			}
		} else {
			// encodeGen.gBase IDENT

			// record the interface for deduplication
			var dup bool
			dup, err = en.DedupWriteIsDup(z.Bid)
			if err != nil {
				return
			}
			if !dup {
				err = z.Bid.EncodeMsg(en)
				if err != nil {
					return
				}
			}
		}
	}

	return
}

// MarshalMsg implements msgp.Marshaler
func (z *Event) MarshalMsg(b []byte) (o []byte, err error) {
	if p, ok := interface{}(z).(msgp.PreSave); ok {
		p.PreSaveHook()
	}

	o = msgp.Require(b, z.Msgsize())

	// honor the omitempty tags
	var empty [4]bool
	fieldsInUse := z.fieldsNotEmpty(empty[:])
	o = msgp.AppendMapHeader(o, fieldsInUse)

	if !empty[0] {
		// string "Etype_zid00_rct"
		o = append(o, 0xaf, 0x45, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x30, 0x5f, 0x72, 0x63, 0x74)
		o = msgp.AppendUint8(o, uint8(z.Etype))
	}

	if !empty[1] {
		// string "NewPerson_zid01_ptr"
		o = append(o, 0xb3, 0x4e, 0x65, 0x77, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x31, 0x5f, 0x70, 0x74, 0x72)
		// marshalGen.gPtr()

		if z.NewPerson == nil {
			o = msgp.AppendNil(o)
		} else {
			// hmm.. no en, no place to check en.DedupWriteIsDup(z)

			o, err = z.NewPerson.MarshalMsg(o) // not is.iface, gen/marshal.go:243
			if err != nil {
				return
			}
		}
	}

	if !empty[2] {
		// string "NewAuction_zid02_ptr"
		o = append(o, 0xb4, 0x4e, 0x65, 0x77, 0x41, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x32, 0x5f, 0x70, 0x74, 0x72)
		// marshalGen.gPtr()

		if z.NewAuction == nil {
			o = msgp.AppendNil(o)
		} else {
			// hmm.. no en, no place to check en.DedupWriteIsDup(z)

			o, err = z.NewAuction.MarshalMsg(o) // not is.iface, gen/marshal.go:243
			if err != nil {
				return
			}
		}
	}

	if !empty[3] {
		// string "Bid_zid03_ptr"
		o = append(o, 0xad, 0x42, 0x69, 0x64, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x33, 0x5f, 0x70, 0x74, 0x72)
		// marshalGen.gPtr()

		if z.Bid == nil {
			o = msgp.AppendNil(o)
		} else {
			// hmm.. no en, no place to check en.DedupWriteIsDup(z)

			o, err = z.Bid.MarshalMsg(o) // not is.iface, gen/marshal.go:243
			if err != nil {
				return
			}
		}
	}

	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Event) UnmarshalMsg(bts []byte) (o []byte, err error) {
	return z.UnmarshalMsgWithCfg(bts, nil)
}
func (z *Event) UnmarshalMsgWithCfg(bts []byte, cfg *msgp.RuntimeConfig) (o []byte, err error) {
	var nbs msgp.NilBitsStack
	nbs.Init(cfg)
	var sawTopNil bool
	if msgp.IsNil(bts) {
		sawTopNil = true
		bts = nbs.PushAlwaysNil(bts[1:])
	}

	var field []byte
	_ = field
	const maxFields19zgensym_e3caedb3b7ec15ca_20 = 4

	// -- templateUnmarshalMsg starts here--
	var totalEncodedFields19zgensym_e3caedb3b7ec15ca_20 uint32
	if !nbs.AlwaysNil {
		totalEncodedFields19zgensym_e3caedb3b7ec15ca_20, bts, err = nbs.ReadMapHeaderBytes(bts)
		if err != nil {
			return
		}
	}
	encodedFieldsLeft19zgensym_e3caedb3b7ec15ca_20 := totalEncodedFields19zgensym_e3caedb3b7ec15ca_20
	missingFieldsLeft19zgensym_e3caedb3b7ec15ca_20 := maxFields19zgensym_e3caedb3b7ec15ca_20 - totalEncodedFields19zgensym_e3caedb3b7ec15ca_20

	var nextMiss19zgensym_e3caedb3b7ec15ca_20 int32 = -1
	var found19zgensym_e3caedb3b7ec15ca_20 [maxFields19zgensym_e3caedb3b7ec15ca_20]bool
	var curField19zgensym_e3caedb3b7ec15ca_20 string

doneWithStruct19zgensym_e3caedb3b7ec15ca_20:
	// First fill all the encoded fields, then
	// treat the remaining, missing fields, as Nil.
	for encodedFieldsLeft19zgensym_e3caedb3b7ec15ca_20 > 0 || missingFieldsLeft19zgensym_e3caedb3b7ec15ca_20 > 0 {
		//fmt.Printf("encodedFieldsLeft: %v, missingFieldsLeft: %v, found: '%v', fields: '%#v'\n", encodedFieldsLeft19zgensym_e3caedb3b7ec15ca_20, missingFieldsLeft19zgensym_e3caedb3b7ec15ca_20, msgp.ShowFound(found19zgensym_e3caedb3b7ec15ca_20[:]), unmarshalMsgFieldOrder19zgensym_e3caedb3b7ec15ca_20)
		if encodedFieldsLeft19zgensym_e3caedb3b7ec15ca_20 > 0 {
			encodedFieldsLeft19zgensym_e3caedb3b7ec15ca_20--
			field, bts, err = nbs.ReadMapKeyZC(bts)
			if err != nil {
				return
			}
			curField19zgensym_e3caedb3b7ec15ca_20 = msgp.UnsafeString(field)
		} else {
			//missing fields need handling
			if nextMiss19zgensym_e3caedb3b7ec15ca_20 < 0 {
				// set bts to contain just mnil (0xc0)
				bts = nbs.PushAlwaysNil(bts)
				nextMiss19zgensym_e3caedb3b7ec15ca_20 = 0
			}
			for nextMiss19zgensym_e3caedb3b7ec15ca_20 < maxFields19zgensym_e3caedb3b7ec15ca_20 && (found19zgensym_e3caedb3b7ec15ca_20[nextMiss19zgensym_e3caedb3b7ec15ca_20] || unmarshalMsgFieldSkip19zgensym_e3caedb3b7ec15ca_20[nextMiss19zgensym_e3caedb3b7ec15ca_20]) {
				nextMiss19zgensym_e3caedb3b7ec15ca_20++
			}
			if nextMiss19zgensym_e3caedb3b7ec15ca_20 == maxFields19zgensym_e3caedb3b7ec15ca_20 {
				// filled all the empty fields!
				break doneWithStruct19zgensym_e3caedb3b7ec15ca_20
			}
			missingFieldsLeft19zgensym_e3caedb3b7ec15ca_20--
			curField19zgensym_e3caedb3b7ec15ca_20 = unmarshalMsgFieldOrder19zgensym_e3caedb3b7ec15ca_20[nextMiss19zgensym_e3caedb3b7ec15ca_20]
		}
		//fmt.Printf("switching on curField: '%v'\n", curField19zgensym_e3caedb3b7ec15ca_20)
		switch curField19zgensym_e3caedb3b7ec15ca_20 {
		// -- templateUnmarshalMsg ends here --

		case "Etype_zid00_rct":
			found19zgensym_e3caedb3b7ec15ca_20[0] = true
			{
				var zgensym_e3caedb3b7ec15ca_21 uint8
				zgensym_e3caedb3b7ec15ca_21, bts, err = nbs.ReadUint8Bytes(bts)

				if err != nil {
					return
				}
				z.Etype = EType(zgensym_e3caedb3b7ec15ca_21)
			}
		case "NewPerson_zid01_ptr":
			found19zgensym_e3caedb3b7ec15ca_20[1] = true
			// unmarshalGen.gPtr(): we have a BaseElem: &gen.BaseElem{Common:gen.Common{vname:"z.NewPerson", alias:"Person", hmp:gen.HasMethodPrefix(nil), zid:0}, ShimToBase:"", ShimFromBase:"", Value:0x16, Convert:false, mustinline:false, needsref:false, isIface:false, isInIfaceSlice:false}

			// unmarshalGen.gPtr(): we have an IDENT:

			if nbs.AlwaysNil {
				if z.NewPerson != nil {
					z.NewPerson.UnmarshalMsg(msgp.OnlyNilSlice)
				}
			} else {
				// not nbs.AlwaysNil
				if msgp.IsNil(bts) {
					bts = bts[1:]
					if nil != z.NewPerson {
						z.NewPerson.UnmarshalMsg(msgp.OnlyNilSlice)
					}
				} else {
					// not nbs.AlwaysNil and not IsNil(bts): have something to read

					if z.NewPerson == nil {
						z.NewPerson = new(Person)
					}

					bts, err = z.NewPerson.UnmarshalMsg(bts)
					if err != nil {
						return
					}
				}
			}
		case "NewAuction_zid02_ptr":
			found19zgensym_e3caedb3b7ec15ca_20[2] = true
			// unmarshalGen.gPtr(): we have a BaseElem: &gen.BaseElem{Common:gen.Common{vname:"z.NewAuction", alias:"Auction", hmp:gen.HasMethodPrefix(nil), zid:0}, ShimToBase:"", ShimFromBase:"", Value:0x16, Convert:false, mustinline:false, needsref:false, isIface:false, isInIfaceSlice:false}

			// unmarshalGen.gPtr(): we have an IDENT:

			if nbs.AlwaysNil {
				if z.NewAuction != nil {
					z.NewAuction.UnmarshalMsg(msgp.OnlyNilSlice)
				}
			} else {
				// not nbs.AlwaysNil
				if msgp.IsNil(bts) {
					bts = bts[1:]
					if nil != z.NewAuction {
						z.NewAuction.UnmarshalMsg(msgp.OnlyNilSlice)
					}
				} else {
					// not nbs.AlwaysNil and not IsNil(bts): have something to read

					if z.NewAuction == nil {
						z.NewAuction = new(Auction)
					}

					bts, err = z.NewAuction.UnmarshalMsg(bts)
					if err != nil {
						return
					}
				}
			}
		case "Bid_zid03_ptr":
			found19zgensym_e3caedb3b7ec15ca_20[3] = true
			// unmarshalGen.gPtr(): we have a BaseElem: &gen.BaseElem{Common:gen.Common{vname:"z.Bid", alias:"Bid", hmp:gen.HasMethodPrefix(nil), zid:0}, ShimToBase:"", ShimFromBase:"", Value:0x16, Convert:false, mustinline:false, needsref:false, isIface:false, isInIfaceSlice:false}

			// unmarshalGen.gPtr(): we have an IDENT:

			if nbs.AlwaysNil {
				if z.Bid != nil {
					z.Bid.UnmarshalMsg(msgp.OnlyNilSlice)
				}
			} else {
				// not nbs.AlwaysNil
				if msgp.IsNil(bts) {
					bts = bts[1:]
					if nil != z.Bid {
						z.Bid.UnmarshalMsg(msgp.OnlyNilSlice)
					}
				} else {
					// not nbs.AlwaysNil and not IsNil(bts): have something to read

					if z.Bid == nil {
						z.Bid = new(Bid)
					}

					bts, err = z.Bid.UnmarshalMsg(bts)
					if err != nil {
						return
					}
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				return
			}
		}
	}
	if nextMiss19zgensym_e3caedb3b7ec15ca_20 != -1 {
		bts = nbs.PopAlwaysNil()
	}

	if sawTopNil {
		bts = nbs.PopAlwaysNil()
	}
	o = bts
	if p, ok := interface{}(z).(msgp.PostLoad); ok {
		p.PostLoadHook()
	}

	return
}

// fields of Event
var unmarshalMsgFieldOrder19zgensym_e3caedb3b7ec15ca_20 = []string{"Etype_zid00_rct", "NewPerson_zid01_ptr", "NewAuction_zid02_ptr", "Bid_zid03_ptr"}

var unmarshalMsgFieldSkip19zgensym_e3caedb3b7ec15ca_20 = []bool{false, false, false, false}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *Event) Msgsize() (s int) {
	s = 1 + 16 + msgp.Uint8Size + 20
	if z.NewPerson == nil {
		s += msgp.NilSize
	} else {
		s += z.NewPerson.Msgsize()
	}
	s += 21
	if z.NewAuction == nil {
		s += msgp.NilSize
	} else {
		s += z.NewAuction.Msgsize()
	}
	s += 14
	if z.Bid == nil {
		s += msgp.NilSize
	} else {
		s += z.Bid.Msgsize()
	}
	return
}

// DecodeMsg implements msgp.Decodable
// We treat empty fields as if we read a Nil from the wire.
func (z *MessageSerialized) DecodeMsg(dc *msgp.Reader) (err error) {
	var sawTopNil bool
	if dc.IsNil() {
		sawTopNil = true
		err = dc.ReadNil()
		if err != nil {
			return
		}
		dc.PushAlwaysNil()
	}

	var field []byte
	_ = field
	const maxFields22zgensym_e3caedb3b7ec15ca_23 = 2

	// -- templateDecodeMsg starts here--
	var totalEncodedFields22zgensym_e3caedb3b7ec15ca_23 uint32
	totalEncodedFields22zgensym_e3caedb3b7ec15ca_23, err = dc.ReadMapHeader()
	if err != nil {
		return
	}
	encodedFieldsLeft22zgensym_e3caedb3b7ec15ca_23 := totalEncodedFields22zgensym_e3caedb3b7ec15ca_23
	missingFieldsLeft22zgensym_e3caedb3b7ec15ca_23 := maxFields22zgensym_e3caedb3b7ec15ca_23 - totalEncodedFields22zgensym_e3caedb3b7ec15ca_23

	var nextMiss22zgensym_e3caedb3b7ec15ca_23 int32 = -1
	var found22zgensym_e3caedb3b7ec15ca_23 [maxFields22zgensym_e3caedb3b7ec15ca_23]bool
	var curField22zgensym_e3caedb3b7ec15ca_23 string

doneWithStruct22zgensym_e3caedb3b7ec15ca_23:
	// First fill all the encoded fields, then
	// treat the remaining, missing fields, as Nil.
	for encodedFieldsLeft22zgensym_e3caedb3b7ec15ca_23 > 0 || missingFieldsLeft22zgensym_e3caedb3b7ec15ca_23 > 0 {
		//fmt.Printf("encodedFieldsLeft: %v, missingFieldsLeft: %v, found: '%v', fields: '%#v'\n", encodedFieldsLeft22zgensym_e3caedb3b7ec15ca_23, missingFieldsLeft22zgensym_e3caedb3b7ec15ca_23, msgp.ShowFound(found22zgensym_e3caedb3b7ec15ca_23[:]), decodeMsgFieldOrder22zgensym_e3caedb3b7ec15ca_23)
		if encodedFieldsLeft22zgensym_e3caedb3b7ec15ca_23 > 0 {
			encodedFieldsLeft22zgensym_e3caedb3b7ec15ca_23--
			field, err = dc.ReadMapKeyPtr()
			if err != nil {
				return
			}
			curField22zgensym_e3caedb3b7ec15ca_23 = msgp.UnsafeString(field)
		} else {
			//missing fields need handling
			if nextMiss22zgensym_e3caedb3b7ec15ca_23 < 0 {
				// tell the reader to only give us Nils
				// until further notice.
				dc.PushAlwaysNil()
				nextMiss22zgensym_e3caedb3b7ec15ca_23 = 0
			}
			for nextMiss22zgensym_e3caedb3b7ec15ca_23 < maxFields22zgensym_e3caedb3b7ec15ca_23 && (found22zgensym_e3caedb3b7ec15ca_23[nextMiss22zgensym_e3caedb3b7ec15ca_23] || decodeMsgFieldSkip22zgensym_e3caedb3b7ec15ca_23[nextMiss22zgensym_e3caedb3b7ec15ca_23]) {
				nextMiss22zgensym_e3caedb3b7ec15ca_23++
			}
			if nextMiss22zgensym_e3caedb3b7ec15ca_23 == maxFields22zgensym_e3caedb3b7ec15ca_23 {
				// filled all the empty fields!
				break doneWithStruct22zgensym_e3caedb3b7ec15ca_23
			}
			missingFieldsLeft22zgensym_e3caedb3b7ec15ca_23--
			curField22zgensym_e3caedb3b7ec15ca_23 = decodeMsgFieldOrder22zgensym_e3caedb3b7ec15ca_23[nextMiss22zgensym_e3caedb3b7ec15ca_23]
		}
		//fmt.Printf("switching on curField: '%v'\n", curField22zgensym_e3caedb3b7ec15ca_23)
		switch curField22zgensym_e3caedb3b7ec15ca_23 {
		// -- templateDecodeMsg ends here --

		case "Key_zid00_bin":
			found22zgensym_e3caedb3b7ec15ca_23[0] = true
			z.Key, err = dc.ReadBytes(z.Key)
			if err != nil {
				return
			}
		case "Value_zid01_bin":
			found22zgensym_e3caedb3b7ec15ca_23[1] = true
			z.Value, err = dc.ReadBytes(z.Value)
			if err != nil {
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				return
			}
		}
	}
	if nextMiss22zgensym_e3caedb3b7ec15ca_23 != -1 {
		dc.PopAlwaysNil()
	}

	if sawTopNil {
		dc.PopAlwaysNil()
	}

	if p, ok := interface{}(z).(msgp.PostLoad); ok {
		p.PostLoadHook()
	}

	return
}

// fields of MessageSerialized
var decodeMsgFieldOrder22zgensym_e3caedb3b7ec15ca_23 = []string{"Key_zid00_bin", "Value_zid01_bin"}

var decodeMsgFieldSkip22zgensym_e3caedb3b7ec15ca_23 = []bool{false, false}

// fieldsNotEmpty supports omitempty tags
func (z *MessageSerialized) fieldsNotEmpty(isempty []bool) uint32 {
	if len(isempty) == 0 {
		return 2
	}
	var fieldsInUse uint32 = 2
	isempty[0] = (len(z.Key) == 0) // string, omitempty
	if isempty[0] {
		fieldsInUse--
	}
	isempty[1] = (len(z.Value) == 0) // string, omitempty
	if isempty[1] {
		fieldsInUse--
	}

	return fieldsInUse
}

// EncodeMsg implements msgp.Encodable
func (z *MessageSerialized) EncodeMsg(en *msgp.Writer) (err error) {
	if p, ok := interface{}(z).(msgp.PreSave); ok {
		p.PreSaveHook()
	}

	// honor the omitempty tags
	var empty_zgensym_e3caedb3b7ec15ca_24 [2]bool
	fieldsInUse_zgensym_e3caedb3b7ec15ca_25 := z.fieldsNotEmpty(empty_zgensym_e3caedb3b7ec15ca_24[:])

	// map header
	err = en.WriteMapHeader(fieldsInUse_zgensym_e3caedb3b7ec15ca_25 + 1)
	if err != nil {
		return err
	}

	// runtime struct type identification for 'MessageSerialized'
	err = en.Append(0xa1, 0x40)
	if err != nil {
		return err
	}
	err = en.WriteStringFromBytes([]byte{0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64})
	if err != nil {
		return err
	}

	if !empty_zgensym_e3caedb3b7ec15ca_24[0] {
		// write "Key_zid00_bin"
		err = en.Append(0xad, 0x4b, 0x65, 0x79, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x30, 0x5f, 0x62, 0x69, 0x6e)
		if err != nil {
			return err
		}
		err = en.WriteBytes(z.Key)
		if err != nil {
			return
		}
	}

	if !empty_zgensym_e3caedb3b7ec15ca_24[1] {
		// write "Value_zid01_bin"
		err = en.Append(0xaf, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x31, 0x5f, 0x62, 0x69, 0x6e)
		if err != nil {
			return err
		}
		err = en.WriteBytes(z.Value)
		if err != nil {
			return
		}
	}

	return
}

// MarshalMsg implements msgp.Marshaler
func (z *MessageSerialized) MarshalMsg(b []byte) (o []byte, err error) {
	if p, ok := interface{}(z).(msgp.PreSave); ok {
		p.PreSaveHook()
	}

	o = msgp.Require(b, z.Msgsize())

	// honor the omitempty tags
	var empty [2]bool
	fieldsInUse := z.fieldsNotEmpty(empty[:])
	o = msgp.AppendMapHeader(o, fieldsInUse)

	if !empty[0] {
		// string "Key_zid00_bin"
		o = append(o, 0xad, 0x4b, 0x65, 0x79, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x30, 0x5f, 0x62, 0x69, 0x6e)
		o = msgp.AppendBytes(o, z.Key)
	}

	if !empty[1] {
		// string "Value_zid01_bin"
		o = append(o, 0xaf, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x31, 0x5f, 0x62, 0x69, 0x6e)
		o = msgp.AppendBytes(o, z.Value)
	}

	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *MessageSerialized) UnmarshalMsg(bts []byte) (o []byte, err error) {
	return z.UnmarshalMsgWithCfg(bts, nil)
}
func (z *MessageSerialized) UnmarshalMsgWithCfg(bts []byte, cfg *msgp.RuntimeConfig) (o []byte, err error) {
	var nbs msgp.NilBitsStack
	nbs.Init(cfg)
	var sawTopNil bool
	if msgp.IsNil(bts) {
		sawTopNil = true
		bts = nbs.PushAlwaysNil(bts[1:])
	}

	var field []byte
	_ = field
	const maxFields26zgensym_e3caedb3b7ec15ca_27 = 2

	// -- templateUnmarshalMsg starts here--
	var totalEncodedFields26zgensym_e3caedb3b7ec15ca_27 uint32
	if !nbs.AlwaysNil {
		totalEncodedFields26zgensym_e3caedb3b7ec15ca_27, bts, err = nbs.ReadMapHeaderBytes(bts)
		if err != nil {
			return
		}
	}
	encodedFieldsLeft26zgensym_e3caedb3b7ec15ca_27 := totalEncodedFields26zgensym_e3caedb3b7ec15ca_27
	missingFieldsLeft26zgensym_e3caedb3b7ec15ca_27 := maxFields26zgensym_e3caedb3b7ec15ca_27 - totalEncodedFields26zgensym_e3caedb3b7ec15ca_27

	var nextMiss26zgensym_e3caedb3b7ec15ca_27 int32 = -1
	var found26zgensym_e3caedb3b7ec15ca_27 [maxFields26zgensym_e3caedb3b7ec15ca_27]bool
	var curField26zgensym_e3caedb3b7ec15ca_27 string

doneWithStruct26zgensym_e3caedb3b7ec15ca_27:
	// First fill all the encoded fields, then
	// treat the remaining, missing fields, as Nil.
	for encodedFieldsLeft26zgensym_e3caedb3b7ec15ca_27 > 0 || missingFieldsLeft26zgensym_e3caedb3b7ec15ca_27 > 0 {
		//fmt.Printf("encodedFieldsLeft: %v, missingFieldsLeft: %v, found: '%v', fields: '%#v'\n", encodedFieldsLeft26zgensym_e3caedb3b7ec15ca_27, missingFieldsLeft26zgensym_e3caedb3b7ec15ca_27, msgp.ShowFound(found26zgensym_e3caedb3b7ec15ca_27[:]), unmarshalMsgFieldOrder26zgensym_e3caedb3b7ec15ca_27)
		if encodedFieldsLeft26zgensym_e3caedb3b7ec15ca_27 > 0 {
			encodedFieldsLeft26zgensym_e3caedb3b7ec15ca_27--
			field, bts, err = nbs.ReadMapKeyZC(bts)
			if err != nil {
				return
			}
			curField26zgensym_e3caedb3b7ec15ca_27 = msgp.UnsafeString(field)
		} else {
			//missing fields need handling
			if nextMiss26zgensym_e3caedb3b7ec15ca_27 < 0 {
				// set bts to contain just mnil (0xc0)
				bts = nbs.PushAlwaysNil(bts)
				nextMiss26zgensym_e3caedb3b7ec15ca_27 = 0
			}
			for nextMiss26zgensym_e3caedb3b7ec15ca_27 < maxFields26zgensym_e3caedb3b7ec15ca_27 && (found26zgensym_e3caedb3b7ec15ca_27[nextMiss26zgensym_e3caedb3b7ec15ca_27] || unmarshalMsgFieldSkip26zgensym_e3caedb3b7ec15ca_27[nextMiss26zgensym_e3caedb3b7ec15ca_27]) {
				nextMiss26zgensym_e3caedb3b7ec15ca_27++
			}
			if nextMiss26zgensym_e3caedb3b7ec15ca_27 == maxFields26zgensym_e3caedb3b7ec15ca_27 {
				// filled all the empty fields!
				break doneWithStruct26zgensym_e3caedb3b7ec15ca_27
			}
			missingFieldsLeft26zgensym_e3caedb3b7ec15ca_27--
			curField26zgensym_e3caedb3b7ec15ca_27 = unmarshalMsgFieldOrder26zgensym_e3caedb3b7ec15ca_27[nextMiss26zgensym_e3caedb3b7ec15ca_27]
		}
		//fmt.Printf("switching on curField: '%v'\n", curField26zgensym_e3caedb3b7ec15ca_27)
		switch curField26zgensym_e3caedb3b7ec15ca_27 {
		// -- templateUnmarshalMsg ends here --

		case "Key_zid00_bin":
			found26zgensym_e3caedb3b7ec15ca_27[0] = true
			if nbs.AlwaysNil || msgp.IsNil(bts) {
				if !nbs.AlwaysNil {
					bts = bts[1:]
				}
				z.Key = z.Key[:0]
			} else {
				z.Key, bts, err = nbs.ReadBytesBytes(bts, z.Key)

				if err != nil {
					return
				}
			}
			if err != nil {
				return
			}
		case "Value_zid01_bin":
			found26zgensym_e3caedb3b7ec15ca_27[1] = true
			if nbs.AlwaysNil || msgp.IsNil(bts) {
				if !nbs.AlwaysNil {
					bts = bts[1:]
				}
				z.Value = z.Value[:0]
			} else {
				z.Value, bts, err = nbs.ReadBytesBytes(bts, z.Value)

				if err != nil {
					return
				}
			}
			if err != nil {
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				return
			}
		}
	}
	if nextMiss26zgensym_e3caedb3b7ec15ca_27 != -1 {
		bts = nbs.PopAlwaysNil()
	}

	if sawTopNil {
		bts = nbs.PopAlwaysNil()
	}
	o = bts
	if p, ok := interface{}(z).(msgp.PostLoad); ok {
		p.PostLoadHook()
	}

	return
}

// fields of MessageSerialized
var unmarshalMsgFieldOrder26zgensym_e3caedb3b7ec15ca_27 = []string{"Key_zid00_bin", "Value_zid01_bin"}

var unmarshalMsgFieldSkip26zgensym_e3caedb3b7ec15ca_27 = []bool{false, false}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *MessageSerialized) Msgsize() (s int) {
	s = 1 + 14 + msgp.BytesPrefixSize + len(z.Key) + 16 + msgp.BytesPrefixSize + len(z.Value)
	return
}

// DecodeMsg implements msgp.Decodable
// We treat empty fields as if we read a Nil from the wire.
func (z *Person) DecodeMsg(dc *msgp.Reader) (err error) {
	var sawTopNil bool
	if dc.IsNil() {
		sawTopNil = true
		err = dc.ReadNil()
		if err != nil {
			return
		}
		dc.PushAlwaysNil()
	}

	var field []byte
	_ = field
	const maxFields28zgensym_e3caedb3b7ec15ca_29 = 8

	// -- templateDecodeMsg starts here--
	var totalEncodedFields28zgensym_e3caedb3b7ec15ca_29 uint32
	totalEncodedFields28zgensym_e3caedb3b7ec15ca_29, err = dc.ReadMapHeader()
	if err != nil {
		return
	}
	encodedFieldsLeft28zgensym_e3caedb3b7ec15ca_29 := totalEncodedFields28zgensym_e3caedb3b7ec15ca_29
	missingFieldsLeft28zgensym_e3caedb3b7ec15ca_29 := maxFields28zgensym_e3caedb3b7ec15ca_29 - totalEncodedFields28zgensym_e3caedb3b7ec15ca_29

	var nextMiss28zgensym_e3caedb3b7ec15ca_29 int32 = -1
	var found28zgensym_e3caedb3b7ec15ca_29 [maxFields28zgensym_e3caedb3b7ec15ca_29]bool
	var curField28zgensym_e3caedb3b7ec15ca_29 string

doneWithStruct28zgensym_e3caedb3b7ec15ca_29:
	// First fill all the encoded fields, then
	// treat the remaining, missing fields, as Nil.
	for encodedFieldsLeft28zgensym_e3caedb3b7ec15ca_29 > 0 || missingFieldsLeft28zgensym_e3caedb3b7ec15ca_29 > 0 {
		//fmt.Printf("encodedFieldsLeft: %v, missingFieldsLeft: %v, found: '%v', fields: '%#v'\n", encodedFieldsLeft28zgensym_e3caedb3b7ec15ca_29, missingFieldsLeft28zgensym_e3caedb3b7ec15ca_29, msgp.ShowFound(found28zgensym_e3caedb3b7ec15ca_29[:]), decodeMsgFieldOrder28zgensym_e3caedb3b7ec15ca_29)
		if encodedFieldsLeft28zgensym_e3caedb3b7ec15ca_29 > 0 {
			encodedFieldsLeft28zgensym_e3caedb3b7ec15ca_29--
			field, err = dc.ReadMapKeyPtr()
			if err != nil {
				return
			}
			curField28zgensym_e3caedb3b7ec15ca_29 = msgp.UnsafeString(field)
		} else {
			//missing fields need handling
			if nextMiss28zgensym_e3caedb3b7ec15ca_29 < 0 {
				// tell the reader to only give us Nils
				// until further notice.
				dc.PushAlwaysNil()
				nextMiss28zgensym_e3caedb3b7ec15ca_29 = 0
			}
			for nextMiss28zgensym_e3caedb3b7ec15ca_29 < maxFields28zgensym_e3caedb3b7ec15ca_29 && (found28zgensym_e3caedb3b7ec15ca_29[nextMiss28zgensym_e3caedb3b7ec15ca_29] || decodeMsgFieldSkip28zgensym_e3caedb3b7ec15ca_29[nextMiss28zgensym_e3caedb3b7ec15ca_29]) {
				nextMiss28zgensym_e3caedb3b7ec15ca_29++
			}
			if nextMiss28zgensym_e3caedb3b7ec15ca_29 == maxFields28zgensym_e3caedb3b7ec15ca_29 {
				// filled all the empty fields!
				break doneWithStruct28zgensym_e3caedb3b7ec15ca_29
			}
			missingFieldsLeft28zgensym_e3caedb3b7ec15ca_29--
			curField28zgensym_e3caedb3b7ec15ca_29 = decodeMsgFieldOrder28zgensym_e3caedb3b7ec15ca_29[nextMiss28zgensym_e3caedb3b7ec15ca_29]
		}
		//fmt.Printf("switching on curField: '%v'\n", curField28zgensym_e3caedb3b7ec15ca_29)
		switch curField28zgensym_e3caedb3b7ec15ca_29 {
		// -- templateDecodeMsg ends here --

		case "id_zid00_u64":
			found28zgensym_e3caedb3b7ec15ca_29[0] = true
			z.ID, err = dc.ReadUint64()
			if err != nil {
				return
			}
		case "name_zid01_str":
			found28zgensym_e3caedb3b7ec15ca_29[1] = true
			z.Name, err = dc.ReadString()
			if err != nil {
				return
			}
		case "emailAddress_zid02_str":
			found28zgensym_e3caedb3b7ec15ca_29[2] = true
			z.EmailAddress, err = dc.ReadString()
			if err != nil {
				return
			}
		case "creditCard_zid03_str":
			found28zgensym_e3caedb3b7ec15ca_29[3] = true
			z.CreditCard, err = dc.ReadString()
			if err != nil {
				return
			}
		case "city_zid04_str":
			found28zgensym_e3caedb3b7ec15ca_29[4] = true
			z.City, err = dc.ReadString()
			if err != nil {
				return
			}
		case "state_zid05_str":
			found28zgensym_e3caedb3b7ec15ca_29[5] = true
			z.State, err = dc.ReadString()
			if err != nil {
				return
			}
		case "dateTime_zid06_i64":
			found28zgensym_e3caedb3b7ec15ca_29[6] = true
			z.DateTime, err = dc.ReadInt64()
			if err != nil {
				return
			}
		case "extra_zid07_str":
			found28zgensym_e3caedb3b7ec15ca_29[7] = true
			z.Extra, err = dc.ReadString()
			if err != nil {
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				return
			}
		}
	}
	if nextMiss28zgensym_e3caedb3b7ec15ca_29 != -1 {
		dc.PopAlwaysNil()
	}

	if sawTopNil {
		dc.PopAlwaysNil()
	}

	if p, ok := interface{}(z).(msgp.PostLoad); ok {
		p.PostLoadHook()
	}

	return
}

// fields of Person
var decodeMsgFieldOrder28zgensym_e3caedb3b7ec15ca_29 = []string{"id_zid00_u64", "name_zid01_str", "emailAddress_zid02_str", "creditCard_zid03_str", "city_zid04_str", "state_zid05_str", "dateTime_zid06_i64", "extra_zid07_str"}

var decodeMsgFieldSkip28zgensym_e3caedb3b7ec15ca_29 = []bool{false, false, false, false, false, false, false, false}

// fieldsNotEmpty supports omitempty tags
func (z *Person) fieldsNotEmpty(isempty []bool) uint32 {
	if len(isempty) == 0 {
		return 8
	}
	var fieldsInUse uint32 = 8
	isempty[0] = (z.ID == 0) // number, omitempty
	if isempty[0] {
		fieldsInUse--
	}
	isempty[1] = (len(z.Name) == 0) // string, omitempty
	if isempty[1] {
		fieldsInUse--
	}
	isempty[2] = (len(z.EmailAddress) == 0) // string, omitempty
	if isempty[2] {
		fieldsInUse--
	}
	isempty[3] = (len(z.CreditCard) == 0) // string, omitempty
	if isempty[3] {
		fieldsInUse--
	}
	isempty[4] = (len(z.City) == 0) // string, omitempty
	if isempty[4] {
		fieldsInUse--
	}
	isempty[5] = (len(z.State) == 0) // string, omitempty
	if isempty[5] {
		fieldsInUse--
	}
	isempty[6] = (z.DateTime == 0) // number, omitempty
	if isempty[6] {
		fieldsInUse--
	}
	isempty[7] = (len(z.Extra) == 0) // string, omitempty
	if isempty[7] {
		fieldsInUse--
	}

	return fieldsInUse
}

// EncodeMsg implements msgp.Encodable
func (z *Person) EncodeMsg(en *msgp.Writer) (err error) {
	if p, ok := interface{}(z).(msgp.PreSave); ok {
		p.PreSaveHook()
	}

	// honor the omitempty tags
	var empty_zgensym_e3caedb3b7ec15ca_30 [8]bool
	fieldsInUse_zgensym_e3caedb3b7ec15ca_31 := z.fieldsNotEmpty(empty_zgensym_e3caedb3b7ec15ca_30[:])

	// map header
	err = en.WriteMapHeader(fieldsInUse_zgensym_e3caedb3b7ec15ca_31 + 1)
	if err != nil {
		return err
	}

	// runtime struct type identification for 'Person'
	err = en.Append(0xa1, 0x40)
	if err != nil {
		return err
	}
	err = en.WriteStringFromBytes([]byte{0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e})
	if err != nil {
		return err
	}

	if !empty_zgensym_e3caedb3b7ec15ca_30[0] {
		// write "id_zid00_u64"
		err = en.Append(0xac, 0x69, 0x64, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x30, 0x5f, 0x75, 0x36, 0x34)
		if err != nil {
			return err
		}
		err = en.WriteUint64(z.ID)
		if err != nil {
			return
		}
	}

	if !empty_zgensym_e3caedb3b7ec15ca_30[1] {
		// write "name_zid01_str"
		err = en.Append(0xae, 0x6e, 0x61, 0x6d, 0x65, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x31, 0x5f, 0x73, 0x74, 0x72)
		if err != nil {
			return err
		}
		err = en.WriteString(z.Name)
		if err != nil {
			return
		}
	}

	if !empty_zgensym_e3caedb3b7ec15ca_30[2] {
		// write "emailAddress_zid02_str"
		err = en.Append(0xb6, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x32, 0x5f, 0x73, 0x74, 0x72)
		if err != nil {
			return err
		}
		err = en.WriteString(z.EmailAddress)
		if err != nil {
			return
		}
	}

	if !empty_zgensym_e3caedb3b7ec15ca_30[3] {
		// write "creditCard_zid03_str"
		err = en.Append(0xb4, 0x63, 0x72, 0x65, 0x64, 0x69, 0x74, 0x43, 0x61, 0x72, 0x64, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x33, 0x5f, 0x73, 0x74, 0x72)
		if err != nil {
			return err
		}
		err = en.WriteString(z.CreditCard)
		if err != nil {
			return
		}
	}

	if !empty_zgensym_e3caedb3b7ec15ca_30[4] {
		// write "city_zid04_str"
		err = en.Append(0xae, 0x63, 0x69, 0x74, 0x79, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x34, 0x5f, 0x73, 0x74, 0x72)
		if err != nil {
			return err
		}
		err = en.WriteString(z.City)
		if err != nil {
			return
		}
	}

	if !empty_zgensym_e3caedb3b7ec15ca_30[5] {
		// write "state_zid05_str"
		err = en.Append(0xaf, 0x73, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x35, 0x5f, 0x73, 0x74, 0x72)
		if err != nil {
			return err
		}
		err = en.WriteString(z.State)
		if err != nil {
			return
		}
	}

	if !empty_zgensym_e3caedb3b7ec15ca_30[6] {
		// write "dateTime_zid06_i64"
		err = en.Append(0xb2, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x36, 0x5f, 0x69, 0x36, 0x34)
		if err != nil {
			return err
		}
		err = en.WriteInt64(z.DateTime)
		if err != nil {
			return
		}
	}

	if !empty_zgensym_e3caedb3b7ec15ca_30[7] {
		// write "extra_zid07_str"
		err = en.Append(0xaf, 0x65, 0x78, 0x74, 0x72, 0x61, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x37, 0x5f, 0x73, 0x74, 0x72)
		if err != nil {
			return err
		}
		err = en.WriteString(z.Extra)
		if err != nil {
			return
		}
	}

	return
}

// MarshalMsg implements msgp.Marshaler
func (z *Person) MarshalMsg(b []byte) (o []byte, err error) {
	if p, ok := interface{}(z).(msgp.PreSave); ok {
		p.PreSaveHook()
	}

	o = msgp.Require(b, z.Msgsize())

	// honor the omitempty tags
	var empty [8]bool
	fieldsInUse := z.fieldsNotEmpty(empty[:])
	o = msgp.AppendMapHeader(o, fieldsInUse)

	if !empty[0] {
		// string "id_zid00_u64"
		o = append(o, 0xac, 0x69, 0x64, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x30, 0x5f, 0x75, 0x36, 0x34)
		o = msgp.AppendUint64(o, z.ID)
	}

	if !empty[1] {
		// string "name_zid01_str"
		o = append(o, 0xae, 0x6e, 0x61, 0x6d, 0x65, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x31, 0x5f, 0x73, 0x74, 0x72)
		o = msgp.AppendString(o, z.Name)
	}

	if !empty[2] {
		// string "emailAddress_zid02_str"
		o = append(o, 0xb6, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x32, 0x5f, 0x73, 0x74, 0x72)
		o = msgp.AppendString(o, z.EmailAddress)
	}

	if !empty[3] {
		// string "creditCard_zid03_str"
		o = append(o, 0xb4, 0x63, 0x72, 0x65, 0x64, 0x69, 0x74, 0x43, 0x61, 0x72, 0x64, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x33, 0x5f, 0x73, 0x74, 0x72)
		o = msgp.AppendString(o, z.CreditCard)
	}

	if !empty[4] {
		// string "city_zid04_str"
		o = append(o, 0xae, 0x63, 0x69, 0x74, 0x79, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x34, 0x5f, 0x73, 0x74, 0x72)
		o = msgp.AppendString(o, z.City)
	}

	if !empty[5] {
		// string "state_zid05_str"
		o = append(o, 0xaf, 0x73, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x35, 0x5f, 0x73, 0x74, 0x72)
		o = msgp.AppendString(o, z.State)
	}

	if !empty[6] {
		// string "dateTime_zid06_i64"
		o = append(o, 0xb2, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x36, 0x5f, 0x69, 0x36, 0x34)
		o = msgp.AppendInt64(o, z.DateTime)
	}

	if !empty[7] {
		// string "extra_zid07_str"
		o = append(o, 0xaf, 0x65, 0x78, 0x74, 0x72, 0x61, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x37, 0x5f, 0x73, 0x74, 0x72)
		o = msgp.AppendString(o, z.Extra)
	}

	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Person) UnmarshalMsg(bts []byte) (o []byte, err error) {
	return z.UnmarshalMsgWithCfg(bts, nil)
}
func (z *Person) UnmarshalMsgWithCfg(bts []byte, cfg *msgp.RuntimeConfig) (o []byte, err error) {
	var nbs msgp.NilBitsStack
	nbs.Init(cfg)
	var sawTopNil bool
	if msgp.IsNil(bts) {
		sawTopNil = true
		bts = nbs.PushAlwaysNil(bts[1:])
	}

	var field []byte
	_ = field
	const maxFields32zgensym_e3caedb3b7ec15ca_33 = 8

	// -- templateUnmarshalMsg starts here--
	var totalEncodedFields32zgensym_e3caedb3b7ec15ca_33 uint32
	if !nbs.AlwaysNil {
		totalEncodedFields32zgensym_e3caedb3b7ec15ca_33, bts, err = nbs.ReadMapHeaderBytes(bts)
		if err != nil {
			return
		}
	}
	encodedFieldsLeft32zgensym_e3caedb3b7ec15ca_33 := totalEncodedFields32zgensym_e3caedb3b7ec15ca_33
	missingFieldsLeft32zgensym_e3caedb3b7ec15ca_33 := maxFields32zgensym_e3caedb3b7ec15ca_33 - totalEncodedFields32zgensym_e3caedb3b7ec15ca_33

	var nextMiss32zgensym_e3caedb3b7ec15ca_33 int32 = -1
	var found32zgensym_e3caedb3b7ec15ca_33 [maxFields32zgensym_e3caedb3b7ec15ca_33]bool
	var curField32zgensym_e3caedb3b7ec15ca_33 string

doneWithStruct32zgensym_e3caedb3b7ec15ca_33:
	// First fill all the encoded fields, then
	// treat the remaining, missing fields, as Nil.
	for encodedFieldsLeft32zgensym_e3caedb3b7ec15ca_33 > 0 || missingFieldsLeft32zgensym_e3caedb3b7ec15ca_33 > 0 {
		//fmt.Printf("encodedFieldsLeft: %v, missingFieldsLeft: %v, found: '%v', fields: '%#v'\n", encodedFieldsLeft32zgensym_e3caedb3b7ec15ca_33, missingFieldsLeft32zgensym_e3caedb3b7ec15ca_33, msgp.ShowFound(found32zgensym_e3caedb3b7ec15ca_33[:]), unmarshalMsgFieldOrder32zgensym_e3caedb3b7ec15ca_33)
		if encodedFieldsLeft32zgensym_e3caedb3b7ec15ca_33 > 0 {
			encodedFieldsLeft32zgensym_e3caedb3b7ec15ca_33--
			field, bts, err = nbs.ReadMapKeyZC(bts)
			if err != nil {
				return
			}
			curField32zgensym_e3caedb3b7ec15ca_33 = msgp.UnsafeString(field)
		} else {
			//missing fields need handling
			if nextMiss32zgensym_e3caedb3b7ec15ca_33 < 0 {
				// set bts to contain just mnil (0xc0)
				bts = nbs.PushAlwaysNil(bts)
				nextMiss32zgensym_e3caedb3b7ec15ca_33 = 0
			}
			for nextMiss32zgensym_e3caedb3b7ec15ca_33 < maxFields32zgensym_e3caedb3b7ec15ca_33 && (found32zgensym_e3caedb3b7ec15ca_33[nextMiss32zgensym_e3caedb3b7ec15ca_33] || unmarshalMsgFieldSkip32zgensym_e3caedb3b7ec15ca_33[nextMiss32zgensym_e3caedb3b7ec15ca_33]) {
				nextMiss32zgensym_e3caedb3b7ec15ca_33++
			}
			if nextMiss32zgensym_e3caedb3b7ec15ca_33 == maxFields32zgensym_e3caedb3b7ec15ca_33 {
				// filled all the empty fields!
				break doneWithStruct32zgensym_e3caedb3b7ec15ca_33
			}
			missingFieldsLeft32zgensym_e3caedb3b7ec15ca_33--
			curField32zgensym_e3caedb3b7ec15ca_33 = unmarshalMsgFieldOrder32zgensym_e3caedb3b7ec15ca_33[nextMiss32zgensym_e3caedb3b7ec15ca_33]
		}
		//fmt.Printf("switching on curField: '%v'\n", curField32zgensym_e3caedb3b7ec15ca_33)
		switch curField32zgensym_e3caedb3b7ec15ca_33 {
		// -- templateUnmarshalMsg ends here --

		case "id_zid00_u64":
			found32zgensym_e3caedb3b7ec15ca_33[0] = true
			z.ID, bts, err = nbs.ReadUint64Bytes(bts)

			if err != nil {
				return
			}
		case "name_zid01_str":
			found32zgensym_e3caedb3b7ec15ca_33[1] = true
			z.Name, bts, err = nbs.ReadStringBytes(bts)

			if err != nil {
				return
			}
		case "emailAddress_zid02_str":
			found32zgensym_e3caedb3b7ec15ca_33[2] = true
			z.EmailAddress, bts, err = nbs.ReadStringBytes(bts)

			if err != nil {
				return
			}
		case "creditCard_zid03_str":
			found32zgensym_e3caedb3b7ec15ca_33[3] = true
			z.CreditCard, bts, err = nbs.ReadStringBytes(bts)

			if err != nil {
				return
			}
		case "city_zid04_str":
			found32zgensym_e3caedb3b7ec15ca_33[4] = true
			z.City, bts, err = nbs.ReadStringBytes(bts)

			if err != nil {
				return
			}
		case "state_zid05_str":
			found32zgensym_e3caedb3b7ec15ca_33[5] = true
			z.State, bts, err = nbs.ReadStringBytes(bts)

			if err != nil {
				return
			}
		case "dateTime_zid06_i64":
			found32zgensym_e3caedb3b7ec15ca_33[6] = true
			z.DateTime, bts, err = nbs.ReadInt64Bytes(bts)

			if err != nil {
				return
			}
		case "extra_zid07_str":
			found32zgensym_e3caedb3b7ec15ca_33[7] = true
			z.Extra, bts, err = nbs.ReadStringBytes(bts)

			if err != nil {
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				return
			}
		}
	}
	if nextMiss32zgensym_e3caedb3b7ec15ca_33 != -1 {
		bts = nbs.PopAlwaysNil()
	}

	if sawTopNil {
		bts = nbs.PopAlwaysNil()
	}
	o = bts
	if p, ok := interface{}(z).(msgp.PostLoad); ok {
		p.PostLoadHook()
	}

	return
}

// fields of Person
var unmarshalMsgFieldOrder32zgensym_e3caedb3b7ec15ca_33 = []string{"id_zid00_u64", "name_zid01_str", "emailAddress_zid02_str", "creditCard_zid03_str", "city_zid04_str", "state_zid05_str", "dateTime_zid06_i64", "extra_zid07_str"}

var unmarshalMsgFieldSkip32zgensym_e3caedb3b7ec15ca_33 = []bool{false, false, false, false, false, false, false, false}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *Person) Msgsize() (s int) {
	s = 1 + 13 + msgp.Uint64Size + 15 + msgp.StringPrefixSize + len(z.Name) + 23 + msgp.StringPrefixSize + len(z.EmailAddress) + 21 + msgp.StringPrefixSize + len(z.CreditCard) + 15 + msgp.StringPrefixSize + len(z.City) + 16 + msgp.StringPrefixSize + len(z.State) + 19 + msgp.Int64Size + 16 + msgp.StringPrefixSize + len(z.Extra)
	return
}

// DecodeMsg implements msgp.Decodable
// We treat empty fields as if we read a Nil from the wire.
func (z *SerdeFormat) DecodeMsg(dc *msgp.Reader) (err error) {
	var sawTopNil bool
	if dc.IsNil() {
		sawTopNil = true
		err = dc.ReadNil()
		if err != nil {
			return
		}
		dc.PushAlwaysNil()
	}

	{
		var zgensym_e3caedb3b7ec15ca_34 uint8
		zgensym_e3caedb3b7ec15ca_34, err = dc.ReadUint8()
		(*z) = SerdeFormat(zgensym_e3caedb3b7ec15ca_34)
	}
	if err != nil {
		return
	}
	if sawTopNil {
		dc.PopAlwaysNil()
	}

	if p, ok := interface{}(z).(msgp.PostLoad); ok {
		p.PostLoadHook()
	}

	return
}

// EncodeMsg implements msgp.Encodable
func (z SerdeFormat) EncodeMsg(en *msgp.Writer) (err error) {
	if p, ok := interface{}(z).(msgp.PreSave); ok {
		p.PreSaveHook()
	}

	err = en.WriteUint8(uint8(z))
	if err != nil {
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z SerdeFormat) MarshalMsg(b []byte) (o []byte, err error) {
	if p, ok := interface{}(z).(msgp.PreSave); ok {
		p.PreSaveHook()
	}

	o = msgp.Require(b, z.Msgsize())
	o = msgp.AppendUint8(o, uint8(z))
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *SerdeFormat) UnmarshalMsg(bts []byte) (o []byte, err error) {
	return z.UnmarshalMsgWithCfg(bts, nil)
}
func (z *SerdeFormat) UnmarshalMsgWithCfg(bts []byte, cfg *msgp.RuntimeConfig) (o []byte, err error) {
	var nbs msgp.NilBitsStack
	nbs.Init(cfg)
	var sawTopNil bool
	if msgp.IsNil(bts) {
		sawTopNil = true
		bts = nbs.PushAlwaysNil(bts[1:])
	}

	{
		var zgensym_e3caedb3b7ec15ca_35 uint8
		zgensym_e3caedb3b7ec15ca_35, bts, err = nbs.ReadUint8Bytes(bts)

		if err != nil {
			return
		}
		(*z) = SerdeFormat(zgensym_e3caedb3b7ec15ca_35)
	}
	if sawTopNil {
		bts = nbs.PopAlwaysNil()
	}
	o = bts
	if p, ok := interface{}(z).(msgp.PostLoad); ok {
		p.PostLoadHook()
	}

	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z SerdeFormat) Msgsize() (s int) {
	s = msgp.Uint8Size
	return
}
