package sharedlog_stream

// Code generated by github.com/tinylib/msgp DO NOT EDIT.

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *ControlMetadata) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Stages":
			var zb0002 uint32
			zb0002, err = dc.ReadMapHeader()
			if err != nil {
				err = msgp.WrapError(err, "Stages")
				return
			}
			if z.Stages == nil {
				z.Stages = make(map[string]uint8, zb0002)
			} else if len(z.Stages) > 0 {
				for key := range z.Stages {
					delete(z.Stages, key)
				}
			}
			for zb0002 > 0 {
				zb0002--
				var za0001 string
				var za0002 uint8
				za0001, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Stages")
					return
				}
				za0002, err = dc.ReadUint8()
				if err != nil {
					err = msgp.WrapError(err, "Stages", za0001)
					return
				}
				z.Stages[za0001] = za0002
			}
		case "Key":
			z.Key, err = dc.ReadBytes(z.Key)
			if err != nil {
				err = msgp.WrapError(err, "Key")
				return
			}
		case "Epoch":
			z.Epoch, err = dc.ReadUint32()
			if err != nil {
				err = msgp.WrapError(err, "Epoch")
				return
			}
		case "InstanceId":
			z.InstanceId, err = dc.ReadUint8()
			if err != nil {
				err = msgp.WrapError(err, "InstanceId")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *ControlMetadata) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 4
	// write "Stages"
	err = en.Append(0x84, 0xa6, 0x53, 0x74, 0x61, 0x67, 0x65, 0x73)
	if err != nil {
		return
	}
	err = en.WriteMapHeader(uint32(len(z.Stages)))
	if err != nil {
		err = msgp.WrapError(err, "Stages")
		return
	}
	for za0001, za0002 := range z.Stages {
		err = en.WriteString(za0001)
		if err != nil {
			err = msgp.WrapError(err, "Stages")
			return
		}
		err = en.WriteUint8(za0002)
		if err != nil {
			err = msgp.WrapError(err, "Stages", za0001)
			return
		}
	}
	// write "Key"
	err = en.Append(0xa3, 0x4b, 0x65, 0x79)
	if err != nil {
		return
	}
	err = en.WriteBytes(z.Key)
	if err != nil {
		err = msgp.WrapError(err, "Key")
		return
	}
	// write "Epoch"
	err = en.Append(0xa5, 0x45, 0x70, 0x6f, 0x63, 0x68)
	if err != nil {
		return
	}
	err = en.WriteUint32(z.Epoch)
	if err != nil {
		err = msgp.WrapError(err, "Epoch")
		return
	}
	// write "InstanceId"
	err = en.Append(0xaa, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x64)
	if err != nil {
		return
	}
	err = en.WriteUint8(z.InstanceId)
	if err != nil {
		err = msgp.WrapError(err, "InstanceId")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *ControlMetadata) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 4
	// string "Stages"
	o = append(o, 0x84, 0xa6, 0x53, 0x74, 0x61, 0x67, 0x65, 0x73)
	o = msgp.AppendMapHeader(o, uint32(len(z.Stages)))
	for za0001, za0002 := range z.Stages {
		o = msgp.AppendString(o, za0001)
		o = msgp.AppendUint8(o, za0002)
	}
	// string "Key"
	o = append(o, 0xa3, 0x4b, 0x65, 0x79)
	o = msgp.AppendBytes(o, z.Key)
	// string "Epoch"
	o = append(o, 0xa5, 0x45, 0x70, 0x6f, 0x63, 0x68)
	o = msgp.AppendUint32(o, z.Epoch)
	// string "InstanceId"
	o = append(o, 0xaa, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x64)
	o = msgp.AppendUint8(o, z.InstanceId)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *ControlMetadata) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Stages":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadMapHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Stages")
				return
			}
			if z.Stages == nil {
				z.Stages = make(map[string]uint8, zb0002)
			} else if len(z.Stages) > 0 {
				for key := range z.Stages {
					delete(z.Stages, key)
				}
			}
			for zb0002 > 0 {
				var za0001 string
				var za0002 uint8
				zb0002--
				za0001, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Stages")
					return
				}
				za0002, bts, err = msgp.ReadUint8Bytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Stages", za0001)
					return
				}
				z.Stages[za0001] = za0002
			}
		case "Key":
			z.Key, bts, err = msgp.ReadBytesBytes(bts, z.Key)
			if err != nil {
				err = msgp.WrapError(err, "Key")
				return
			}
		case "Epoch":
			z.Epoch, bts, err = msgp.ReadUint32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Epoch")
				return
			}
		case "InstanceId":
			z.InstanceId, bts, err = msgp.ReadUint8Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "InstanceId")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *ControlMetadata) Msgsize() (s int) {
	s = 1 + 7 + msgp.MapHeaderSize
	if z.Stages != nil {
		for za0001, za0002 := range z.Stages {
			_ = za0002
			s += msgp.StringPrefixSize + len(za0001) + msgp.Uint8Size
		}
	}
	s += 4 + msgp.BytesPrefixSize + len(z.Key) + 6 + msgp.Uint32Size + 11 + msgp.Uint8Size
	return
}
