package sharedlog_stream

// Code generated by github.com/tinylib/msgp DO NOT EDIT.

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *LogEntryMeta) DecodeMsg(dc *msgp.Reader) (err error) {
	{
		var zb0001 uint8
		zb0001, err = dc.ReadUint8()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		(*z) = LogEntryMeta(zb0001)
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z LogEntryMeta) EncodeMsg(en *msgp.Writer) (err error) {
	err = en.WriteUint8(uint8(z))
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z LogEntryMeta) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	o = msgp.AppendUint8(o, uint8(z))
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *LogEntryMeta) UnmarshalMsg(bts []byte) (o []byte, err error) {
	{
		var zb0001 uint8
		zb0001, bts, err = msgp.ReadUint8Bytes(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		(*z) = LogEntryMeta(zb0001)
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z LogEntryMeta) Msgsize() (s int) {
	s = msgp.Uint8Size
	return
}

// DecodeMsg implements msgp.Decodable
func (z *StreamLogEntry) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "topicName":
			var zb0002 uint32
			zb0002, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "TopicName")
				return
			}
			if cap(z.TopicName) >= int(zb0002) {
				z.TopicName = (z.TopicName)[:zb0002]
			} else {
				z.TopicName = make([]string, zb0002)
			}
			for za0001 := range z.TopicName {
				z.TopicName[za0001], err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "TopicName", za0001)
					return
				}
			}
		case "payload":
			z.Payload, err = dc.ReadBytes(z.Payload)
			if err != nil {
				err = msgp.WrapError(err, "Payload")
				return
			}
		case "injTsMs":
			z.InjTsMs, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "InjTsMs")
				return
			}
		case "tid":
			z.TaskId, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "TaskId")
				return
			}
		case "mseq":
			z.MsgSeqNum, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "MsgSeqNum")
				return
			}
		case "te":
			z.TaskEpoch, err = dc.ReadUint16()
			if err != nil {
				err = msgp.WrapError(err, "TaskEpoch")
				return
			}
		case "meta":
			z.Meta, err = dc.ReadUint8()
			if err != nil {
				err = msgp.WrapError(err, "Meta")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *StreamLogEntry) EncodeMsg(en *msgp.Writer) (err error) {
	// omitempty: check for empty values
	zb0001Len := uint32(7)
	var zb0001Mask uint8 /* 7 bits */
	if z.Payload == nil {
		zb0001Len--
		zb0001Mask |= 0x2
	}
	if z.InjTsMs == 0 {
		zb0001Len--
		zb0001Mask |= 0x4
	}
	if z.TaskId == 0 {
		zb0001Len--
		zb0001Mask |= 0x8
	}
	if z.MsgSeqNum == 0 {
		zb0001Len--
		zb0001Mask |= 0x10
	}
	if z.TaskEpoch == 0 {
		zb0001Len--
		zb0001Mask |= 0x20
	}
	if z.Meta == 0 {
		zb0001Len--
		zb0001Mask |= 0x40
	}
	// variable map header, size zb0001Len
	err = en.Append(0x80 | uint8(zb0001Len))
	if err != nil {
		return
	}
	if zb0001Len == 0 {
		return
	}
	// write "topicName"
	err = en.Append(0xa9, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x4e, 0x61, 0x6d, 0x65)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.TopicName)))
	if err != nil {
		err = msgp.WrapError(err, "TopicName")
		return
	}
	for za0001 := range z.TopicName {
		err = en.WriteString(z.TopicName[za0001])
		if err != nil {
			err = msgp.WrapError(err, "TopicName", za0001)
			return
		}
	}
	if (zb0001Mask & 0x2) == 0 { // if not empty
		// write "payload"
		err = en.Append(0xa7, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64)
		if err != nil {
			return
		}
		err = en.WriteBytes(z.Payload)
		if err != nil {
			err = msgp.WrapError(err, "Payload")
			return
		}
	}
	if (zb0001Mask & 0x4) == 0 { // if not empty
		// write "injTsMs"
		err = en.Append(0xa7, 0x69, 0x6e, 0x6a, 0x54, 0x73, 0x4d, 0x73)
		if err != nil {
			return
		}
		err = en.WriteInt64(z.InjTsMs)
		if err != nil {
			err = msgp.WrapError(err, "InjTsMs")
			return
		}
	}
	if (zb0001Mask & 0x8) == 0 { // if not empty
		// write "tid"
		err = en.Append(0xa3, 0x74, 0x69, 0x64)
		if err != nil {
			return
		}
		err = en.WriteUint64(z.TaskId)
		if err != nil {
			err = msgp.WrapError(err, "TaskId")
			return
		}
	}
	if (zb0001Mask & 0x10) == 0 { // if not empty
		// write "mseq"
		err = en.Append(0xa4, 0x6d, 0x73, 0x65, 0x71)
		if err != nil {
			return
		}
		err = en.WriteUint64(z.MsgSeqNum)
		if err != nil {
			err = msgp.WrapError(err, "MsgSeqNum")
			return
		}
	}
	if (zb0001Mask & 0x20) == 0 { // if not empty
		// write "te"
		err = en.Append(0xa2, 0x74, 0x65)
		if err != nil {
			return
		}
		err = en.WriteUint16(z.TaskEpoch)
		if err != nil {
			err = msgp.WrapError(err, "TaskEpoch")
			return
		}
	}
	if (zb0001Mask & 0x40) == 0 { // if not empty
		// write "meta"
		err = en.Append(0xa4, 0x6d, 0x65, 0x74, 0x61)
		if err != nil {
			return
		}
		err = en.WriteUint8(z.Meta)
		if err != nil {
			err = msgp.WrapError(err, "Meta")
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *StreamLogEntry) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// omitempty: check for empty values
	zb0001Len := uint32(7)
	var zb0001Mask uint8 /* 7 bits */
	if z.Payload == nil {
		zb0001Len--
		zb0001Mask |= 0x2
	}
	if z.InjTsMs == 0 {
		zb0001Len--
		zb0001Mask |= 0x4
	}
	if z.TaskId == 0 {
		zb0001Len--
		zb0001Mask |= 0x8
	}
	if z.MsgSeqNum == 0 {
		zb0001Len--
		zb0001Mask |= 0x10
	}
	if z.TaskEpoch == 0 {
		zb0001Len--
		zb0001Mask |= 0x20
	}
	if z.Meta == 0 {
		zb0001Len--
		zb0001Mask |= 0x40
	}
	// variable map header, size zb0001Len
	o = append(o, 0x80|uint8(zb0001Len))
	if zb0001Len == 0 {
		return
	}
	// string "topicName"
	o = append(o, 0xa9, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x4e, 0x61, 0x6d, 0x65)
	o = msgp.AppendArrayHeader(o, uint32(len(z.TopicName)))
	for za0001 := range z.TopicName {
		o = msgp.AppendString(o, z.TopicName[za0001])
	}
	if (zb0001Mask & 0x2) == 0 { // if not empty
		// string "payload"
		o = append(o, 0xa7, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64)
		o = msgp.AppendBytes(o, z.Payload)
	}
	if (zb0001Mask & 0x4) == 0 { // if not empty
		// string "injTsMs"
		o = append(o, 0xa7, 0x69, 0x6e, 0x6a, 0x54, 0x73, 0x4d, 0x73)
		o = msgp.AppendInt64(o, z.InjTsMs)
	}
	if (zb0001Mask & 0x8) == 0 { // if not empty
		// string "tid"
		o = append(o, 0xa3, 0x74, 0x69, 0x64)
		o = msgp.AppendUint64(o, z.TaskId)
	}
	if (zb0001Mask & 0x10) == 0 { // if not empty
		// string "mseq"
		o = append(o, 0xa4, 0x6d, 0x73, 0x65, 0x71)
		o = msgp.AppendUint64(o, z.MsgSeqNum)
	}
	if (zb0001Mask & 0x20) == 0 { // if not empty
		// string "te"
		o = append(o, 0xa2, 0x74, 0x65)
		o = msgp.AppendUint16(o, z.TaskEpoch)
	}
	if (zb0001Mask & 0x40) == 0 { // if not empty
		// string "meta"
		o = append(o, 0xa4, 0x6d, 0x65, 0x74, 0x61)
		o = msgp.AppendUint8(o, z.Meta)
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *StreamLogEntry) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "topicName":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "TopicName")
				return
			}
			if cap(z.TopicName) >= int(zb0002) {
				z.TopicName = (z.TopicName)[:zb0002]
			} else {
				z.TopicName = make([]string, zb0002)
			}
			for za0001 := range z.TopicName {
				z.TopicName[za0001], bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "TopicName", za0001)
					return
				}
			}
		case "payload":
			z.Payload, bts, err = msgp.ReadBytesBytes(bts, z.Payload)
			if err != nil {
				err = msgp.WrapError(err, "Payload")
				return
			}
		case "injTsMs":
			z.InjTsMs, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "InjTsMs")
				return
			}
		case "tid":
			z.TaskId, bts, err = msgp.ReadUint64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "TaskId")
				return
			}
		case "mseq":
			z.MsgSeqNum, bts, err = msgp.ReadUint64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "MsgSeqNum")
				return
			}
		case "te":
			z.TaskEpoch, bts, err = msgp.ReadUint16Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "TaskEpoch")
				return
			}
		case "meta":
			z.Meta, bts, err = msgp.ReadUint8Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Meta")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *StreamLogEntry) Msgsize() (s int) {
	s = 1 + 10 + msgp.ArrayHeaderSize
	for za0001 := range z.TopicName {
		s += msgp.StringPrefixSize + len(z.TopicName[za0001])
	}
	s += 8 + msgp.BytesPrefixSize + len(z.Payload) + 8 + msgp.Int64Size + 4 + msgp.Uint64Size + 5 + msgp.Uint64Size + 3 + msgp.Uint16Size + 5 + msgp.Uint8Size
	return
}
