// Code generated by "stringer -type=GuaranteeMth"; DO NOT EDIT.

package exactly_once_intr

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AT_LEAST_ONCE-0]
	_ = x[TWO_PHASE_COMMIT-1]
	_ = x[EPOCH_MARK-2]
}

const _GuaranteeMth_name = "AT_LEAST_ONCETWO_PHASE_COMMITEPOCH_MARK"

var _GuaranteeMth_index = [...]uint8{0, 13, 29, 39}

func (i GuaranteeMth) String() string {
	if i >= GuaranteeMth(len(_GuaranteeMth_index)-1) {
		return "GuaranteeMth(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _GuaranteeMth_name[_GuaranteeMth_index[i]:_GuaranteeMth_index[i+1]]
}
