// Code generated by "stringer -type=EpochMark"; DO NOT EDIT.

package commtypes

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EMPTY-0]
	_ = x[EPOCH_END-1]
	_ = x[ABORT-2]
	_ = x[SCALE_FENCE-3]
	_ = x[FENCE-4]
	_ = x[STREAM_END-5]
}

const _EpochMark_name = "EMPTYEPOCH_ENDABORTSCALE_FENCEFENCESTREAM_END"

var _EpochMark_index = [...]uint8{0, 5, 14, 19, 30, 35, 45}

func (i EpochMark) String() string {
	if i >= EpochMark(len(_EpochMark_index)-1) {
		return "EpochMark(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EpochMark_name[_EpochMark_index[i]:_EpochMark_index[i+1]]
}
