package commtypes

// Code generated by github.com/tinylib/msgp DO NOT EDIT.

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *KeyAndWindowStartTsSerialized) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "k":
			z.KeySerialized, err = dc.ReadBytes(z.KeySerialized)
			if err != nil {
				err = msgp.WrapError(err, "KeySerialized")
				return
			}
		case "ts":
			z.WindowStartTs, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "WindowStartTs")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *KeyAndWindowStartTsSerialized) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 2
	// write "k"
	err = en.Append(0x82, 0xa1, 0x6b)
	if err != nil {
		return
	}
	err = en.WriteBytes(z.KeySerialized)
	if err != nil {
		err = msgp.WrapError(err, "KeySerialized")
		return
	}
	// write "ts"
	err = en.Append(0xa2, 0x74, 0x73)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.WindowStartTs)
	if err != nil {
		err = msgp.WrapError(err, "WindowStartTs")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *KeyAndWindowStartTsSerialized) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 2
	// string "k"
	o = append(o, 0x82, 0xa1, 0x6b)
	o = msgp.AppendBytes(o, z.KeySerialized)
	// string "ts"
	o = append(o, 0xa2, 0x74, 0x73)
	o = msgp.AppendInt64(o, z.WindowStartTs)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *KeyAndWindowStartTsSerialized) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "k":
			z.KeySerialized, bts, err = msgp.ReadBytesBytes(bts, z.KeySerialized)
			if err != nil {
				err = msgp.WrapError(err, "KeySerialized")
				return
			}
		case "ts":
			z.WindowStartTs, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "WindowStartTs")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *KeyAndWindowStartTsSerialized) Msgsize() (s int) {
	s = 1 + 2 + msgp.BytesPrefixSize + len(z.KeySerialized) + 3 + msgp.Int64Size
	return
}
