package commtypes

// Code generated by github.com/tinylib/msgp DO NOT EDIT.

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *OffsetMarker) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "offset":
			z.Offset, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "Offset")
				return
			}
		case "mark":
			err = z.Mark.DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "Mark")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *OffsetMarker) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 2
	// write "offset"
	err = en.Append(0x82, 0xa6, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74)
	if err != nil {
		return
	}
	err = en.WriteUint64(z.Offset)
	if err != nil {
		err = msgp.WrapError(err, "Offset")
		return
	}
	// write "mark"
	err = en.Append(0xa4, 0x6d, 0x61, 0x72, 0x6b)
	if err != nil {
		return
	}
	err = z.Mark.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "Mark")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *OffsetMarker) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 2
	// string "offset"
	o = append(o, 0x82, 0xa6, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74)
	o = msgp.AppendUint64(o, z.Offset)
	// string "mark"
	o = append(o, 0xa4, 0x6d, 0x61, 0x72, 0x6b)
	o, err = z.Mark.MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "Mark")
		return
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *OffsetMarker) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "offset":
			z.Offset, bts, err = msgp.ReadUint64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Offset")
				return
			}
		case "mark":
			bts, err = z.Mark.UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "Mark")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *OffsetMarker) Msgsize() (s int) {
	s = 1 + 7 + msgp.Uint64Size + 5 + z.Mark.Msgsize()
	return
}
